[1852]feat: move images by dragging on the editor
facebook/lexical pull request #2027
Opened 2022-04-28 15:05 UTC by LuciNyan

## Description
- I added a div layer to the LazyImage component to change the body of the drag from an image to a div so that I could work with dataTransfer.setDragImage on safari to remove the default shadow that occurs when dragging.
- because when dragging occurs, although we can see the cursor in the document with our mouse movement, but in fact that is a new cursor only when dragging, we can not getSelection ().getRange (0) to get the exact location of the cursor, so I implemented a `getDragSelection` method, the I've tested it on chrome, safari and firefox on a mac and it all seems to work fine, but I'm not sure if it can handle all scenarios.
- I extended the `INSERT_IMAGE_COMMAND` directive to handle two more parameters `width` and `height` so that the resized image will remain the same size after the move

## Related Issues 📦
#1852

2022-04-28 15:28 UTC, LuciNyan commented
Could you give me a few pointers with flow. I've come across some flow hints that are confusing me, for example:

`Cannot call '$isImageNode' with 'node' bound to 'node' because 'LexicalNode' [1] is incompatible with 'LexicalNode' [2].
[incompatible-call]`

But the two `LexicalNode` are actually the same thing...

2022-04-28 15:31 UTC, acywatson commented
> Could you give me a few pointers with flow. I've come across some flow hints that are confusing me, for example:
> 
> `Cannot call '$isImageNode' with 'node' bound to 'node' because 'LexicalNode' [1] is incompatible with 'LexicalNode' [2]. [incompatible-call]`
> 
> But the two `LexicalNode` are actually the same thing...

IIRC this usually means you're importing something from the wrong place - usually a relative import that should be absolute.

2022-04-28 15:33 UTC, LuciNyan commented
> 

Thanks for the reminder!

2022-04-28 15:36 UTC, acywatson requested changes

2022-04-28 15:51 UTC, fantactuka commented on packages/lexical-rich-text/src/index.js
> +import {$isImageNode} from 'lexical-playground/src/nodes/ImageNode';
It can register to DROP_COMMAND and DRAGSTART_COMMAND commands @ playground with higher priority and check for image node / node selection. Then rich text plugin remains intact

2022-04-28 15:53 UTC, acywatson commented on packages/lexical-rich-text/src/index.js
> +import {$isImageNode} from 'lexical-playground/src/nodes/ImageNode';
Oh yea, that's the right approach. My bad for not looking closely enough at the intent here.

2022-04-28 16:24 UTC, LuciNyan commented
> Could you add a video showing how it works?

Ok! I have added it.

2022-04-29 03:13 UTC, LuciNyan commented on packages/lexical-rich-text/src/index.js
> +import {$isImageNode} from 'lexical-playground/src/nodes/ImageNode';
@fantactuka 

Thank you very much! this is a very useful reminder.

2022-04-29 07:33 UTC, yuzhouu commented
Hi, how about use the original image as drag preview?

2022-04-29 09:11 UTC, LuciNyan commented
> Hi, how about use the original image as drag preview?

When the size of the image is large, a large preview image appears when dragging. To the user, this looks like an unnecessary visual distraction.

2022-05-10 23:45 UTC, acywatson commented
> Hello @acywatson.
> 
> I have tested drag and drop on windows and mac with different browsers (including firefox) and everything works fine, but when I run my e2e tests with playwright, some of the tests with firefox don't work, I have tried a lot but still can't solve the problem. For example, I can't get `event.rangeParent` and `event.rangeOffset` correctly when testing. Could you tell me what I should do?
> 
> Thanks!

@LuciNyan So sorry - I missed this comment. Let me take a look a this and see what's going on.

2022-05-11 04:00 UTC, LuciNyan commented
> > Hello @acywatson.
> > I have tested drag and drop on windows and mac with different browsers (including firefox) and everything works fine, but when I run my e2e tests with playwright, some of the tests with firefox don't work, I have tried a lot but still can't solve the problem. For example, I can't get `event.rangeParent` and `event.rangeOffset` correctly when testing. Could you tell me what I should do?
> > Thanks!
> 
> @LuciNyan So sorry - I missed this comment. Let me take a look a this and see what's going on.

No worries! and I have resolved the conflict and resubmitted the code. There are a few minor changes.

Thanks for your response!

2022-05-15 16:36 UTC, LuciNyan commented
> > Hello @acywatson.
> > I have tested drag and drop on windows and mac with different browsers (including firefox) and everything works fine, but when I run my e2e tests with playwright, some of the tests with firefox don't work, I have tried a lot but still can't solve the problem. For example, I can't get `event.rangeParent` and `event.rangeOffset` correctly when testing. Could you tell me what I should do?
> > Thanks!
> 
> @LuciNyan So sorry - I missed this comment. Let me take a look a this and see what's going on.

I was wondering if I could not test against firefox for the above reason. I've spent a lot of time trying to solve the problem that firefox behaves differently in practice than when running tests in playwright, but there seems to be no effective solution so far. And there doesn't seem to be a better way to get the range on drag and drop. 

Could you give me some advice?

2022-05-15 18:18 UTC, acywatson commented
> > > Hello @acywatson.
> > > I have tested drag and drop on windows and mac with different browsers (including firefox) and everything works fine, but when I run my e2e tests with playwright, some of the tests with firefox don't work, I have tried a lot but still can't solve the problem. For example, I can't get `event.rangeParent` and `event.rangeOffset` correctly when testing. Could you tell me what I should do?
> > > Thanks!
> > 
> > 
> > @LuciNyan So sorry - I missed this comment. Let me take a look a this and see what's going on.
> 
> I was wondering if I could not test against firefox for the above reason. I've spent a lot of time trying to solve the problem that firefox behaves differently in practice than when running tests in playwright, but there seems to be no effective solution so far. And there doesn't seem to be a better way to get the range on drag and drop.
> 
> Could you give me some advice?

It looks like the failure is actually happening only on Firefox for Windows, which is interesting. I don't have immediate access to a Windows machine to try to repro this, but I think @fantactuka might?

Interesting that you tested it on both windows and mac - I wonder if there's a version difference that might explain the different behaviors? I couldn't find anything in the release logs.

Doing some reading on the Drag Event API, it looks like there are some particularly divergent browser behaviors here. One thing. I found interesting is that rangeParent and rangeOffset don't seem to be part of the public API (which is probably why you had to delcare them as global types). One thing I might suggest is trying to use document.caretPositionFromPoint as your fallback when caretRangeFromPoint is not available (instead of event.rangeParent and event.rangeOffset).

https://developer.mozilla.org/en-US/docs/Web/API/Document/caretPositionFromPoint

Can you give that a try and see what happens? If you can provide more details on what's happening in playwright (are rangeParent and rangeOffset undefined? Set to zero?) Perhaps we can file a bug with Playwright and see if we can get more information there.

Thanks for your effort and persistence here!

2022-05-16 20:31 UTC, fantactuka commented
> Hello @acywatson.
> 
> I've tried document.caretPositionFromPoint and it works perfectly fine in practice, but in playwright it gets the same wrong value as event.rangeParent and event.rangeOffset. For example, if there is a line with `1234` and I drag the image to the middle of `23`, the correct `rangeOffset` should be 2, but in playwright we get 0. I would like to add that I tested the drag and drop on my windows virtual machine, I did not test it on a real windows machine. It looks like it would be nice to have a windows user to help look at this test.
> 
> Thanks for your advice!

Did some testing on windows machine and came to the same results as you did. After some offline discussion with @acywatson we thought it could be outdated playwright-core fork that used firefox 93 vs 99-100 on desktop. But updating to the latest version didn't change anything.

Tried to do dragging in steps (bring image into paragraphs end, and then run second drag into the middle), splitting dragging into multiple steps (moving by delta between two points), and each approach had same issue with firefox

2022-05-17 02:24 UTC, LuciNyan commented
> > Hello @acywatson.
> > I've tried document.caretPositionFromPoint and it works perfectly fine in practice, but in playwright it gets the same wrong value as event.rangeParent and event.rangeOffset. For example, if there is a line with `1234` and I drag the image to the middle of `23`, the correct `rangeOffset` should be 2, but in playwright we get 0. I would like to add that I tested the drag and drop on my windows virtual machine, I did not test it on a real windows machine. It looks like it would be nice to have a windows user to help look at this test.
> > Thanks for your advice!
> 
> Did some testing on windows machine and came to the same results as you did. After some offline discussion with @acywatson we thought it could be outdated playwright-core fork that used firefox 93 vs 99-100 on desktop. But updating to the latest version didn't change anything.
> 
> Tried to do dragging in steps (bring image into paragraph end, and then run second drag into the middle); splitting dragging into multiple steps (moving by delta between two points), and each approach had same issue with firefox

Yes, I've tried all of these too, including waiting a bit at the end of a drag before dropping it, distributing the movement, etc., and all have the same problem. I'd like to know what we should do next on this feature.

Thank you very much for your help!

2022-05-17 14:07 UTC, fantactuka commented on packages/lexical-playground/src/plugins/ImagesPlugin.ts
> +  } else {
```suggestion
  } else if (event.rangeParent) {
    domSelection.collapse(event.rangeParent, event.rangeOffset || 0);
    range = domSelection.getRangeAt(0);
  } else {
```

2022-05-17 14:09 UTC, fantactuka commented
Tried to debug it on windows a bit more, but no luck with getting proper rangeOffset. Let me report it as a bug into playwright, and we can have e2e fork for now

2022-05-17 17:22 UTC, LuciNyan commented
Hello @acywatson.

There is still a requested change that needs your approval and I would like to know if there is anything else I need to change.

2022-05-18 14:52 UTC, LuciNyan commented
Hello @acywatson.

I noticed that the PR had not been closed, and I wondered if it had forgotten to be merged. XD

2022-05-18 15:49 UTC, acywatson commented
> Hello @acywatson.
> 
> I noticed that the PR had not been closed, and I wondered if it had forgotten to be merged.

No, we just leave PRs open after approval for a bit sometimes to give other team members a chance to look at them. In this case, we were also discussing the long-term implications of the FF issue a bit internally. I think this is safe to merge now. Thanks again!

2022-05-18 15:49 UTC, merged

2024-09-20 18:32 UTC, PauloMendees commented
Can someone help-me?

When I try to drag/move the Image in the editor, nothing happens, here is some of my code

`  const draggable = isSelected && $isNodeSelection(selection) && !isResizing;
  const isFocused = isSelected || isResizing;
  return (
    <Suspense fallback={null}>
      <>
        <div draggable={draggable}>
          {isLoadError ? (
            <BrokenImage />
          ) : (
            <LazyImage
              className={
                isFocused
                  ? `focused ${$isNodeSelection(selection) ? 'cursor-grabbing' : ''}`
                  : null
              }
              src={src}
              altText={altText}
              imageRef={imageRef}
              width={width}
              height={height}
              maxWidth={maxWidth}
              onError={() => setIsLoadError(true)}
            />
          )}
        </div>
        {resizable && $isNodeSelection(selection) && isFocused && (
          <ImageResizer
            editor={editor}
            imageRef={imageRef}
            maxWidth={maxWidth}
            onResizeStart={onResizeStart}
            onResizeEnd={onResizeEnd}
          />
        )}
      </>
    </Suspense>
  );
}`

`function LazyImage({
  altText,
  className,
  imageRef,
  src,
  width,
  height,
  maxWidth,
  onError
}: {
  altText: string;
  className: string | null;
  height: 'inherit' | number;
  imageRef: { current: null | HTMLImageElement };
  maxWidth: number;
  src: string;
  width: 'inherit' | number;
  onError: () => void;
}): JSX.Element {
  useSuspenseImage(src);
  return (
    <img
      className={className || undefined}
      src={src}
      alt={altText}
      ref={imageRef}
      style={{
        height,
        maxWidth,
        width
      }}
      onError={onError}
      draggable="false"
    />
  );
}`