Add Toolbar Color Picker
facebook/lexical pull request #2152
Opened 2022-05-12 09:49 UTC by WinmezzZ

fix: #892

2022-05-12 13:20 UTC, fantactuka commented
Looks great!
Icon is a bit too similar to formatting dropdown (A vs Aa), but can't see any alternatives in bootstrap icons, maybe other folks will have suggestions

2022-05-12 13:21 UTC, fantactuka approved these changes

2022-05-12 15:06 UTC, WinmezzZ commented
> Looks great! Icon is a bit too similar to formatting dropdown (A vs Aa), but can't see any alternatives in bootstrap icons, maybe other folks will have suggestions

I think so.

 Maybe you can provide a better icon for it.

2022-05-12 18:00 UTC, WinmezzZ commented
What's wrong with checks?

2022-05-13 22:23 UTC, acywatson requested changes

2022-05-13 22:23 UTC, acywatson commented on packages/lexical-playground/src/ui/DropDown.tsx
> +          typeof buttonLabel === 'string' ? buttonLabel : buttonAriaLabel
This is what's breaking all the tests - some of the tests rely in finding elements by ARIA label, but the components also provide buttonLabel. With this change, you're overriding all the buttonAriaLabels with the value of buttonLabel (unless buttonLabel is a react component, which it isn't in every other case except yours).

I'm not really sure why you'd want the ARIA label to be JSX anyway. I would change this and just pass in button label and aria label separately.

2022-05-14 08:53 UTC, WinmezzZ commented on packages/lexical-playground/src/ui/DropDown.tsx
> +          typeof buttonLabel === 'string' ? buttonLabel : buttonAriaLabel
Got it, thanks.

I will fix this

2022-05-14 09:21 UTC, WinmezzZ commented
@acywatson 
Had been changed but also breaked the test?

2022-05-15 09:00 UTC, WinmezzZ commented
Need review changes

2022-05-15 17:12 UTC, acywatson approved these changes
Looks right to me now, thanks!

Would love to see an e2e test or two for this, but since it's relying on existing core library functionality and not exposing a new plugin for users to consume, I think we are OK without it for now.

Thanks for taking the time to put this together!

2022-05-16 22:14 UTC, merged