Apply colspan and rowspan from external tables
facebook/lexical pull request #2165
Opened 2022-05-13 17:34 UTC by mmarkelov

close #2101

2022-05-13 18:58 UTC, acywatson commented
Thanks for the PR! Looks like a few issues with the tests - I think the assertions just need to be updated to accommodate the changes.

2022-05-13 19:00 UTC, mmarkelov commented
@acywatson yeah! My bad, forgot tests

2022-05-13 21:30 UTC, acywatson approved these changes
I'm good with this, but will let @tylerjbainbridge take a quick look as the owner of tables.

2022-05-13 21:30 UTC, acywatson commented on packages/lexical-table/src/LexicalTableCellNode.js
> +  __colSpan: number;
The only concern I have here is that this may technically be a breaking change since it will change the schema of the serialized editor state. We are working on a way to decouple the serialization format from the node properties, after which this won't really be a problem. In the meantime, it looks like we're only adding properties and we have defaults here that should make it backwards compatible.

2022-05-13 21:45 UTC, acywatson requested changes
Actually, looks like we still have test failures - the CI was showing a green check earlier and fooled me 😅

2022-05-14 07:26 UTC, mmarkelov commented on packages/lexical-table/src/LexicalTableCellNode.js
> +  __colSpan: number;
@acywatson idk, i suppose that i can implement the logic when these default properties won't be added during the serialization

2022-05-14 16:04 UTC, tylerjbainbridge requested changes
I'm pretty sure this is going to break selection and a lot of table operations (insert row/column, delete row/column, apply header state, etc) because they iterate through the table assuming each row has the same amount of columns using basic for-loops. There needs to be some new logic that accounts for colspan & rowspan added here. 

This feature is planned but will require changing a lot of core code within [`TableSelection`](https://github.com/facebook/lexical/blob/main/packages/lexical-table/src/LexicalTableSelection.js), [`GridSelection`](https://github.com/facebook/lexical/blob/84948d70fc499f8e638ed7c6e51eda3135c9fff5/packages/lexical/src/LexicalSelection.js#L334), and [`TableUtils`](https://github.com/facebook/lexical/blob/main/packages/lexical-table/src/LexicalTableUtils.js).

Happy to approve the PR once support is added in these places & the tests pass, but that's going to be a lot of work.

2022-05-15 18:38 UTC, mmarkelov commented
@tylerjbainbridge yeah, now. I see. Thanks for your comment. Will close it for a now, cause I tried to implement all cases, but it requires a lot of changes

2022-05-15 18:38 UTC, closed without merging