Feat: Add clear formatting button to playground
facebook/lexical pull request #2295
Opened 2022-05-30 09:29 UTC by im-adithya

https://user-images.githubusercontent.com/64399555/170961978-128faa38-23e9-4cdb-8e03-63e5f64d8f11.mp4

**Note:** Is it okay to leave the hashtag as is? Because lexical changes the node from text to hashtag whenever a string starts with "#". But due to changing the background color to default, the light blue background of the hashtag is being removed.

2022-05-30 10:33 UTC, trueadm commented
Could use an e2e test to confirm it works right?

2022-05-30 12:20 UTC, im-adithya commented
@trueadm Can you please let me know about handling the hashtag node as discussed above? That would help me in writing e2e for this functionality!

2022-05-30 14:26 UTC, thegreatercurve requested changes
LGTM! Just clarified some of the behaviour in the comments above which should also answer the hashtag question

2022-05-30 14:26 UTC, thegreatercurve commented on packages/lexical-playground/src/plugins/ToolbarPlugin.tsx
> +    });
Apologies, I was basing the original behaviour for this on the "Paste without format" behaviour in Google Docs and Word, but the "Clear All Formatting" behaviour is slightly different in that it doesn't necessarily remove links, hashtags, or list elements. 

It just clears the format and any text color, but NOT the size. More from [the Word docs here](https://support.microsoft.com/en-us/office/clear-all-text-formatting-c094c4da-7f09-4cea-9a8d-c166949c9c80): 
> You can easily clear all formatting (such as bold, underline, italics, color, superscript, subscript, and more) from your text and return your text to its default formatting styles.

I think therefore we can just do the below:

```suggestion
    activeEditor.update(() => {
      const selection = $getSelection();
      if ($isRangeSelection(selection)) {
        $selectAll(selection);
        selection.getNodes().forEach((node) => {
          if ($isTextNode(node)) {
            node.setFormat(0);
          }
        });
        $patchStyleText(selection, {
          'background-color': '#fff',
          color: '#000',
          'font-family': 'Arial',
        });
      }
      activeEditor.dispatchCommand(FORMAT_ELEMENT_COMMAND, 'left');
    });
```

2022-05-30 14:26 UTC, thegreatercurve commented on packages/lexical-playground/src/plugins/ToolbarPlugin.tsx
> +        aria-label="Clear">
```suggestion
        aria-label="Clear all text formatting">
```

2022-05-30 14:26 UTC, thegreatercurve commented on packages/lexical-playground/src/plugins/ToolbarPlugin.tsx
> +        title="Clear Formatting"
Might be a little clearer for accessibility: 
```suggestion
        title="Clear text formatting"
```

2022-05-30 15:29 UTC, im-adithya commented on packages/lexical-playground/src/plugins/ToolbarPlugin.tsx
> +        onClick={clearFormatting}
Thanks for the valuable inputs! Made all the necessary changes!

2022-05-30 15:53 UTC, im-adithya commented
@thegreatercurve shouldn't we leave the nodes which already have some pre-specified text-color (quote node and link node) or background-color (hashtags, mentions) while using the `$patchStyleText` helper function? Attaching these screenshots for reference:

Before Clearing:
![Screenshot from 2022-05-30 21-20-36](https://user-images.githubusercontent.com/64399555/171026881-3f4e5913-7b67-431a-aed5-bc6d55aba487.png)

After Clearing:
![Screenshot from 2022-05-30 21-20-33](https://user-images.githubusercontent.com/64399555/171026870-d2dc090b-95e3-407e-b4c2-378ba52c60e2.png)

2022-05-30 17:52 UTC, thegreatercurve commented
> @thegreatercurve shouldn't we leave the nodes which already have some pre-specified text-color (quote node and link node) or background-color (hashtags, mentions) while using the `$patchStyleText` helper function? Attaching these screenshots for reference:
> 
> Before Clearing: ![Screenshot from 2022-05-30 21-20-36](https://user-images.githubusercontent.com/64399555/171026881-3f4e5913-7b67-431a-aed5-bc6d55aba487.png)
> 
> After Clearing: ![Screenshot from 2022-05-30 21-20-33](https://user-images.githubusercontent.com/64399555/171026870-d2dc090b-95e3-407e-b4c2-378ba52c60e2.png)

@im-adithya Very good point. You're right, in other editors, they essentially reset the non-TextNodes to its original styles. 

In that case, I think we can still solve the issue with the existing APIs. There is a `setStyle` method on TextNode, which we can use to reset things such as font, and highlight or text colors. 

So, if you remove `$patchStyleText`, you can then do something like the below in your loop:

```js
 if ($isTextNode(node) || $isHashTahNode(node) || $isMentionNode(node)) {
    node.setFormat(0);
    node.setStyle('');
 }
```

2022-05-31 10:41 UTC, im-adithya commented
Done! Checking for just `$textNode` worked fine as the other two were extending from it!

2022-05-31 13:39 UTC, thegreatercurve approved these changes
LGTM. Thanks for working on this @im-adithya.

2022-05-31 13:39 UTC, merged