Fix/code highlighting split
facebook/lexical pull request #2382
Opened 2022-06-09 18:46 UTC by lateefazeez

## Split Code Highlighting Plugin
 - Split code highlighting plugin into highlighting and editor shortcuts (indent multiple lines, keep tab level on a new line

https://user-images.githubusercontent.com/53082437/172921529-6383f004-c075-4f9e-96ac-a38cb50459a3.mov

)

2022-06-09 18:54 UTC, fantactuka requested changes

2022-06-09 18:54 UTC, fantactuka commented on packages/lexical-code/src/CodeHighlighter.ts
> +export function getLastCodeHighlightNodeOfLine(
This one should probably go into EditorShortcuts as it's not used here

2022-06-09 18:54 UTC, fantactuka commented on packages/lexical-code/src/CodeHighlighter.ts
> +export class CodeNode extends ElementNode {
Do you mind extracting CodeNode & all related helpers (including $isCodeNode, $createCodeNode) into own file, and same for CodeHighlightingNode. It should make highlighting plugin file easier to navigate through

2022-06-09 18:54 UTC, fantactuka commented on packages/lexical-code/src/EditorShortcuts.ts
> +export function getStartOfCodeInLine(anchor: LexicalNode): {
This one does not seem to be used anywhere else, so no need to export it. Same applies to few other exports: try to move helpers into plugins files where they are used and only export node classes + helpers that are used as API ($isCodeNode, registerCodeHighlighting, etc). The rest can remain as local helpers without exporting

2022-06-10 16:44 UTC, lateefazeez commented
## Changes
 - I rearranged the codes, created separate files for CodeHighlightNode, CodeNode, Code Highlighter and EditorShortcuts as requested. Please review.

2022-06-15 17:32 UTC, fantactuka approved these changes
Couple minor changes needed, but looks good otherwise 👍

2022-06-15 17:32 UTC, fantactuka commented on packages/lexical-code/LexicalCode.d.ts
> +declare function registerCodeIndent(editor: LexicalEditor): () => void;
Let's remove `registerCodeIndent` from d.ts file for now, it is part of `registerCodeHighlighting` for now. I think we should eventually split them and call separately, but it'll be a breaking change so it's not urgent to do now

2022-06-15 17:32 UTC, fantactuka commented on packages/lexical-code/LexicalCode.d.ts
> +  threshold: number,
It should be optional argument, with `Infinity` as default value

2022-06-15 17:32 UTC, fantactuka commented on packages/lexical-playground/src/plugins/CodeHighlightPlugin.ts
> +    return registerCodeHighlighting(editor, 50);
Let's have it 10000 for a playground

2022-06-15 17:51 UTC, lateefazeez commented on packages/lexical-playground/src/plugins/CodeHighlightPlugin.ts
> +    return registerCodeHighlighting(editor, 50);
Okay, will do same as above

2022-07-05 21:53 UTC, lateefazeez commented
I updated this code to resolve all conflicts, but somehow not showing up here. So I created a new PR for this. Link below

https://github.com/MLH-Fellowship/lexical/pull/5/

2022-07-05 21:53 UTC, closed without merging