Fetch Lexical State Tree in DevTools App
facebook/lexical pull request #2510
Opened 2022-06-24 19:15 UTC by noi5e

<img width="703" alt="Screen Shot 2022-06-24 at 11 37 52 AM" src="https://user-images.githubusercontent.com/4361605/175646447-e5a40711-6b72-419a-aa71-4727f6eba2fe.png">

# Features
- Injects a script via [devtools.inspectedWindow.eval()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/inspectedWindow/eval) onto the page to `registerUpdateListener` and listen to `editorState` changes
- `editorState` changes get passed up to the browser extension [background script](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background)
- The background script messages the React app in the DevTools panel, which updates the UI via hooks
- Tested in Firefox, Chrome, and Edge
- **Other Feature:** popup window for browser icon:
<img width="383" alt="Screen Shot 2022-06-24 at 12 12 37 PM" src="https://user-images.githubusercontent.com/4361605/175650301-74a78b6e-6c00-4172-9bb6-d3376f3ce3d9.png">

## Note on the App Flow
Currently the `editorState` updates get passed into the browser extension this way:
  1. User loads the extension, `content.js` sets up a [messaging connection](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onConnect) with `background.js`
  3. User opens the browser's DevTools console, `devtools.js` injects a `registerUpdateListener` onto the page
  4. When the `editorState` changes, the page does a `window.postMessage`
  5. `content.js` reads the `postMessage` and passes the `editorState` up to `background.js`
  6. If the Lexical DevTools panel has been opened, `background.js` sends a message to `App.tsx`, where the UI is updated.

The messaging is complicated right now for a few reasons. The main one is that I'm trying to not put too many things into `devtools.inspectedWindow.eval()` for security reasons. In the future, I think the messaging could be made a lot simpler and handled completely by `devtools.js`, without needing a content or background script. For example: 
  1. `devtools.js` sets up a messaging connection between the inspected window, the Lexical DevTools React app, and itself.
  2. `devtools.js` injects a `registerUpdateListener` onto the page AND a listener for `window.postMessage`
  3. `devtools.js` messages the Lexical DevTools React app itself

---
Developer Tools Web Extension Planning Issue: #2127

2022-06-24 19:18 UTC, noi5e commented on packages/lexical-devtools/public/background.js
> +chrome.runtime.onConnect.addListener(function (port) {
I'm still trying to find a way to not disable the linter here. `chrome` is defined within the browser extension of course. 

I experimented a bit with making a custom `.eslintrc` like someone suggested, but I didn't have much luck. Pointers welcome!

2022-06-24 19:20 UTC, noi5e commented on packages/lexical-devtools/src/App.tsx
> +  const [editorState, setEditorState] = useState<object>({});
Temporary linter disable here, because the app isn't technically doing anything with `editorState` yet. I will remove it in the next PR.

2022-06-24 19:22 UTC, noi5e commented on packages/lexical-devtools/src/App.tsx
> +  }, []);
TBH, I could use some guidance in best practices for making these hooks, there's a lot of knowledge gaps I have here.

2022-06-24 19:26 UTC, noi5e commented
<img width="921" alt="Screen Shot 2022-06-24 at 12 24 04 PM" src="https://user-images.githubusercontent.com/4361605/175653252-6810532e-3586-4421-9aec-47fa2b102968.png">

Okay, I guess now's a good time to start learning TypeScript. 📖

2022-06-27 13:20 UTC, thegreatercurve requested changes
This looks good to me. My only concern is that we're using JS in most of these files when we should instead be using TS.

You will need to add an `input` and `output` to your Vite config [like in this example](https://github.com/JohnBra/vite-web-extension/blob/main/vite.config.ts#L25-L37) to transform the TS into JS.

2022-06-27 13:20 UTC, thegreatercurve commented on packages/lexical-devtools/src/App.tsx
> +  }, []);
This hook seems to be correct, apart from updating the dependency array to include the ref. React should provide you with a linting error telling you what should be included in the dependency array.

This is a useful guide on how to use effect hooks: https://blog.logrocket.com/guide-to-react-useeffect-hook

2022-06-28 06:06 UTC, noi5e commented on packages/lexical-devtools/public/background.js
> +  port.onMessage.addListener(function (message) {
Done!

2022-06-28 06:18 UTC, noi5e commented on packages/lexical-devtools/public/devtools.js
> +  `,
> This logic can be outside the eval so it lints correctly, and then you can call it via a function call in a string literal i.e. .eval(${registerAllUpdateListeners()}``

Gave this a shot, didn't quite run as expected, although I might have the syntax wrong:
<img width="748" alt="Screen Shot 2022-06-27 at 10 45 27 PM" src="https://user-images.githubusercontent.com/4361605/176106850-a2c79bb2-5940-420d-bcaf-f351307bfe30.png">

Seems to be a scoping thing maybe?

<img width="657" alt="Screen Shot 2022-06-27 at 10 45 37 PM" src="https://user-images.githubusercontent.com/4361605/176106883-fc7d9a67-9616-46fb-9bdd-9aa86925328a.png">

2022-06-28 06:18 UTC, noi5e commented on packages/lexical-devtools/src/App.tsx
> +    port.current = chrome.runtime.connect();
Done!

2022-06-28 06:25 UTC, noi5e commented on packages/lexical-devtools/src/App.tsx
> +  }, []);
> This hook seems to be correct, apart from updating the dependency array to include the ref. React should provide you with a linting error telling you what should be included in the dependency array.

Added the port object here in the latest commits. 

This is the current state of the linter errors:
<img width="653" alt="Screen Shot 2022-06-27 at 11 21 12 PM" src="https://user-images.githubusercontent.com/4361605/176107749-21e63b7c-d9d2-4ad6-a6a1-c3aa6503f590.png">

I think I need to define a `Port` type and describe `onMessage` and `postMessage` as its methods. Is that right? Looks like this might be the main barrier to getting this merged. Will have to study up on this.

2022-06-28 06:46 UTC, noi5e commented on packages/lexical-devtools/public/background.js
> +chrome.runtime.onConnect.addListener(function (port) {
Addressed here, yet to be implemented: https://github.com/facebook/lexical/pull/2510#discussion_r907140259

2022-06-28 07:01 UTC, noi5e commented on packages/lexical-devtools/public/background.js
> +chrome.runtime.onConnect.addListener(function (port) {
> This looks good to me. My only concern is that we're using JS in most of these files when we should instead be using TS.

> You will need to add an input and output to your Vite config [like in this example](https://github.com/JohnBra/vite-web-extension/blob/main/vite.config.ts#L25-L37) to transform the TS into JS.

Nice, this weekend I was working on exactly that in a separate branch. I just opened up a separate PR for this change at #2540.

> This should be something like the below. You can then add the chrome windows types using npm i --save-dev @types/chrome

2022-06-28 17:18 UTC, noi5e commented on packages/lexical-devtools/src/App.tsx
> +  }, []);
Since @thegreatercurve's will be away for a bit, curious if @fantactuka or @acywatson have a suggestion here. 

I'm starting from scratch with TypeScript and a little guidance could help since this is the main thing blocking this PR right now:

> I think I need to define a Port type and describe onMessage and postMessage as its methods. Is that right? Looks like this might be the main barrier to getting this merged. Will have to study up on this.

2022-06-28 23:03 UTC, thegreatercurve commented on packages/lexical-devtools/src/App.tsx
> +  }, []);
@noi5e Use `CMD+Click` to click on `connect()` to see what return type is being coming back from `port.current`. It looks like an empty object, hence why you're getting the errors.

Ideally, the return type from port.current should look like the below: 
```ts
type CurrentPort = {
  postMessage: (
    message: {
       name: string; 
       tabId: string;
       type: string 
    }
  ) => void;
  onMessage: {
    addListener: (message: {editorState: React.SetStateAction<object>}) => void
  }
}
```

For the moment though, these are quite advanced types to try to define yourself, especially if you're not experience with TS, so "cast" the types to `any` to remove the type checks, disable the lint warning, and one of us can then do a fix PR on top to add the types. 

This would look like:
```ts
(port.current as any).postWindow(
(port.current as any).onMessage.
```

2022-06-29 16:44 UTC, acywatson commented on packages/lexical-devtools/public/background.js
> +chrome.runtime.onConnect.addListener(function (port) {
I think we can keep separate PRs, if that's easier for you to manage.

2022-06-29 18:55 UTC, acywatson commented on packages/lexical-devtools/public/content.js
> +  type: 'FROM_CONTENT',
can these be constants somewhere in a different shared module, maybe?

2022-06-30 20:15 UTC, noi5e commented
Okay, I think I've taken care of all the TypeScript errors in DevTools (or disabled the linter so they can be taken care of in #2540).

This still isn't passing CI for some reason. The failures look like they don't have anything to do with my code: 
<img width="1035" alt="Screen Shot 2022-06-30 at 1 02 17 PM" src="https://user-images.githubusercontent.com/4361605/176768063-3588612e-137f-4be5-9793-1b51423d619f.png">
<img width="910" alt="Screen Shot 2022-06-30 at 1 02 42 PM" src="https://user-images.githubusercontent.com/4361605/176768096-588a5fe3-e4ab-4d7e-89e6-1e06191c4c95.png">

I did install `@types/chrome` in the last commit. Maybe there's a chance that did something weird to the dependency tree?

2022-07-04 20:33 UTC, noi5e commented on packages/lexical-devtools/public/content.js
> +  type: 'FROM_CONTENT',
> can these be constants somewhere in a different shared module, maybe?

Addressing this and moving the discussion [here](https://github.com/facebook/lexical/pull/2540#issuecomment-1174292738)

2022-07-04 20:43 UTC, noi5e commented
<img width="1047" alt="Screen Shot 2022-07-04 at 1 37 09 PM" src="https://user-images.githubusercontent.com/4361605/177214403-d2a9e16c-b561-4821-8510-a660c657e7e3.png">

Just one failing test now, seems like it doesn't have anything to do with my changes.

Once this passes CI, this will be ready to merge.

Just to keep tabs on the main suggestions from code review:
1. `chrome.runtime.onConnect.addListener` - This needs `@types/chrome` to be installed, which is done in #2540.
2. `port.current.onMessage.addListener` - Still don't know enough TypeScript to handle this, @thegreatercurve suggesting changing this type to `any`, and then having staff write the type properly.
3. ES6-style imports and modules in `content.js` and `background.js` - handled in #2540

2022-07-05 17:23 UTC, noi5e commented
I think this is ready to merge! @fantactuka @thegreatercurve @acywatson

2022-07-05 17:50 UTC, merged