fix: Verify if there are text nodes before continue
facebook/lexical pull request #2616
Opened 2022-07-08 16:11 UTC by Negan1911

There are cases (like, when the only item in selection is a decorator block) that you will not have text nodes in selection.

This used to fail with `Cannot read property getFormatFlags of undefined` previously, now it currently returns abruptly without failing.

2022-07-08 16:38 UTC, zurfyx approved these changes
While the user should ideally do some validation beforehand this makes sense to me (especially when triggered via a command), thank you!

2022-07-08 16:38 UTC, zurfyx commented on packages/lexical/src/LexicalSelection.ts
> +    if (!selectedTextNodesLength) return;
```suggestion
    if (selectedTextNodesLength === 0) {
      return;
    }
```

2022-07-08 16:52 UTC, acywatson commented
Looks good - I just approved the CI run, so let's make sure that passes before merging.

2022-07-08 18:13 UTC, acywatson requested changes
Looks like we have some failing e2e and unit tests.  You can ignore the console.warn - I'll fix that in a separate PR.

2022-07-08 22:36 UTC, Negan1911 commented
I found that I broke some valid test cases by returning without toggling the format in, this should do it now :)

2022-08-01 18:57 UTC, acywatson approved these changes
Sorry, didn't mean to block this for so long - looks like all tests are passing now.

2022-08-01 18:57 UTC, merged