Port ASCII State Tree to Browser Extension
facebook/lexical pull request #2625
Opened 2022-07-11 00:33 UTC by noi5e

## Features
- Fetches JSON `editorState._nodeMap` on initial app loading, and on subsequent updates.
- Renders tree `<Node>`s recursively.

https://user-images.githubusercontent.com/4361605/178168320-1aca6b43-cb8b-4325-9483-f4bce942a4cb.mov

2022-07-11 00:34 UTC, noi5e commented
I expect there to be tons of TypeScript errors when the CI finishes... I'm going to spend the next few days brushing up on TypeScript to get past them, but I thought I'd make the PR early and get feedback on it simultaneously.

2022-07-11 00:38 UTC, noi5e commented on packages/lexical-devtools/src/panel/components/App/index.tsx
> +      setNodeMap(newNodeMap);
I found out that `editorState` has a `toJSON()` method, so this will probably be simplified a lot in the next PR.

2022-07-11 00:38 UTC, noi5e commented on packages/lexical-devtools/src/content/index.ts
> +      editorState: {nodeMap},
See [comment](https://github.com/facebook/lexical/pull/2625/files#r917471663)

2022-07-11 00:41 UTC, noi5e commented on packages/lexical-devtools/src/panel/components/Node/index.tsx
> +          ))}
There's some really cool [layout stuff](https://github.com/facebook/lexical/blob/30ad13bcc637dfc61cb15aaa45e3d13bcf7d9602/packages/lexical-react/src/LexicalTreeView.tsx) going on with `<pre>` in the existing `LexicalTreeView` which I hope can be implemented later.

2022-07-11 10:15 UTC, thegreatercurve commented on packages/lexical-devtools/src/content/index.ts
> +const IS_FIREFOX = navigator.userAgent.indexOf('Firefox') >= 0;
There's already a utility method for `IS_FIREFOX` you can import instead

2022-07-11 10:15 UTC, thegreatercurve commented on packages/lexical-devtools/src/content/index.ts
> +      editorState: {nodeMap},
Why do we need the Firefox logic if this is only initially going to be working on Chrome?

2022-07-11 10:15 UTC, thegreatercurve commented on packages/lexical-devtools/src/panel/components/App/index.tsx
> +        </>
```suggestion
          <div className="loading-view">
            <p>Loading...</p>
          </div>
```

2022-07-11 11:15 UTC, thegreatercurve commented on packages/lexical-devtools/src/panel/components/TreeView/index.tsx
> +    const children = [];
```suggestion
    const children: Array<NodeKey >= [];
```

2022-07-12 02:54 UTC, noi5e commented on packages/lexical-devtools/src/content/index.ts
> +      editorState: {nodeMap},
> Why do we need the Firefox logic if this is only initially going to be working on Chrome?

Oops, just to clarify:
- The app currently works in Chrome, Firefox, and Edge (manually tested everything). I use the `chrome` namespace because `chrome` works in all three browsers (even Firefox). `browser`, the other alternative, doesn't work in Chrome and Edge ([docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities#chrome._and_browser._namespace))
- I think I'll be able to get rid of the `IS_FIREFOX` logic completely. I didn't realize that `getEditorState()` has a `toJSON()` method, which will make this logic totally unneeded. (It's kind of a long story, but has to do with serialization differences between the different browsers) It should be a simple fix, but I'll focus on getting over the TypeScript hurdle in this PR first.

2022-07-12 03:35 UTC, noi5e commented on packages/lexical-devtools/src/background/index.ts
> +    const tabId = port?.sender?.tab?.id || message.tabId;
I had to modify this after rebasing on your changes because `port.sender` is `undefined` in messages from the DevTools app. Just to summarize the locations which send messages to `background.js`:

- `content.js` 
  - the browser extension injects this content script, once per browser tab.
  - **`port.sender` is defined in messages from `content.js` (`FROM_CONTENT`)**
- `devtools.js`
  - this script runs an `eval()` statement to inject a `registerUpdateListener` into the tab (which we can't do from a content script).
  - the `eval()` statement also sets up messaging between the page and the background script.
  - `devtools.js` also sets up the actual DevTools panel, and loads the `index.html` where the React app is located
  - **`port.sender` is defined in messages from the page (`FROM_PAGE`)**
- `App.tsx`
  - this is the React app within the DevTools panel.
  - for some reason, **`port.sender` is UNDEFINED in messages from the React app (`FROM_APP`)**
  - my workaround for this is to lookup the `inspectedWindow`'s `tabId` and [post that with the message](https://github.com/MLH-Fellowship/lexical/blob/f3aafca34c33183e3cd5d70c072dca716cf2f906/packages/lexical-devtools/src/panel/components/App/index.tsx#L26-L31)

**TLDR:** The logic here has to accommodate messages `FROM_APP`, where `port.sender` is `undefined`, but `message.tabId` **IS**.

Right now I have `const tabId = port?.sender?.tab?.id || message.tabId;` as a workaround. I'm sure that's not great, but `port.sender.tab.id || message.tabId` throws a TS `possibly undefined` error. Any suggestions?

2022-07-12 03:42 UTC, noi5e commented on packages/lexical-devtools/src/background/index.ts
> +    const tabId = port?.sender?.tab?.id || message.tabId;
Side note: I know the whole messaging setup is pretty complicated. 

I think it's possible to just have the page communicate with the DevTools panel, or at least remove `content.js` as the middleman. But I think both scenarios would require putting more messaging (and possible security risk?) in the `eval()` statement. Saving that as a stretch goal for now.

2022-07-13 09:49 UTC, thegreatercurve requested changes
LGTM, but just requesting changes for the TS errors.

2022-07-13 09:49 UTC, thegreatercurve commented on packages/lexical-devtools/src/background/index.ts
> +    const tabId = port?.sender?.tab?.id || message.tabId;
> TLDR: The logic here has to accommodate messages FROM_APP, where port.sender is undefined, but message.tabId IS.
> Right now I have const tabId = port?.sender?.tab?.id || message.tabId; as a workaround. I'm sure that's not great, but port.sender.tab.id || message.tabId throws a TS possibly undefined error. Any suggestions?

@noi5e can you just put it in a conditional and reassign it if only one of the cases is met else return out of the function? Something like the below:
```js
let tabId;

if (port.sender && port.sender.tab) {
    tabId = port.sender.tab.id;
} else if (message.tabId) {
    tabId = message.tabId;
} else {
    return;
}

```

2022-07-13 23:18 UTC, noi5e commented on packages/lexical-devtools/src/background/index.ts
> +    const tabId = port?.sender?.tab?.id || message.tabId;
> @noi5e can you just put it in a conditional and reassign it if only one of the cases is met, else return out of the function? Something like the below:

Thanks, that did it! 🎊

2022-07-15 01:26 UTC, noi5e commented
@thegreatercurve Looks like we're not in bad shape here! 

Can you look at the types I made and let me know how to improve them?

2022-07-15 09:22 UTC, thegreatercurve commented on packages/lexical-devtools/src/panel/components/App/index.css
> +  font-size: 24px;
You might as well use `ems`

```suggestion
  font-size: 2em;
```

2022-07-15 09:22 UTC, thegreatercurve commented on packages/lexical-devtools/src/panel/components/App/index.css
> +  font-size: 36px;
```suggestion
  font-size: 3em;
```

2022-07-15 09:24 UTC, thegreatercurve commented on packages/lexical-devtools/src/panel/components/App/index.tsx
> +  );
Would this just work? 

```suggestion
  const [nodeMap, setNodeMap] = useState<DevToolsTree>({});
```

2022-07-15 09:25 UTC, thegreatercurve commented on packages/lexical-devtools/types.ts
> +  [x: string]: any;
This should be fine if we're planning on indiscriminately printing all keys and values on the node object.

2022-07-15 09:25 UTC, thegreatercurve approved these changes
LGTM @noi5e. A couple of suggested changes, but otherwise good to merge.

2022-07-15 21:14 UTC, acywatson commented on packages/lexical-devtools/src/panel/components/App/index.tsx
>        port.current.onMessage.addListener(
Do you need to remove this listener ever?

2022-07-15 21:17 UTC, acywatson approved these changes
Nice work

2022-07-15 21:39 UTC, noi5e commented on packages/lexical-devtools/types.ts
> +  [x: string]: any;
> This should be fine if we're planning on indiscriminately printing all keys and values on the node object.

Yeah, I hope so, mostly I was just copying from the existing [LexicalNode](https://github.com/facebook/lexical/blob/645227ebd0f61942d48897b03b0701a4da884508/packages/lexical/src/LexicalNode.ts#L160-L166). Can revisit later once I get a sense of what properties DevTools will be dealing with

2022-07-15 21:54 UTC, noi5e commented
> Do you need to remove this listener ever?

Oops yeah, forgot to do this. Just updated the `useEffect` hooks to return a `port.disconnect`.

After the CI passes, I think this is finally good to merge!

2022-07-15 22:35 UTC, merged