TextNode setFormat/setDetail to accept a number only
facebook/lexical pull request #3038
Opened 2022-09-20 02:07 UTC by zurfyx

Initially I thought it was best to do a full replacement in favor for constants https://github.com/facebook/lexical/pull/3037 just like we have for commands now. Constants are easy to follow and type.

I quitted for two reasons:
1. User churn
2. No bundle size win as I expected. Unfortunately there's no good way to minimize ES Module bundles and the constant names have a decent size

However, what we have now is still not professional. A setter and a getter should return the same value, ideally what we store on the node.

In this PR I'm making setFormat and setFormat to work exclusively with numbers and additional provide the toggle and has functions for both.

Closes https://github.com/facebook/lexical/pull/3037

2022-09-21 16:45 UTC, fantactuka commented on packages/lexical/src/nodes/LexicalTextNode.ts
> +  toggleDetail(detail: TextDetailType): this {
Will it benefit to have this exposed vs toggleUnmergeable/toggleDirectionless? It will bring similar confusion that you've tried to avoid when setDetail takes number, and toggleDetail uses strings

2022-09-21 17:48 UTC, zurfyx commented on packages/lexical/src/nodes/LexicalTextNode.ts
> +  toggleDetail(detail: TextDetailType): this {
@fantactuka What about format (bold, italics, etc), should they be toggleBold/toggleItalics etc?

2022-09-21 17:50 UTC, fantactuka commented on packages/lexical/src/nodes/LexicalTextNode.ts
> +  toggleDetail(detail: TextDetailType): this {
Ah, I see now 👍

2022-09-21 17:53 UTC, fantactuka approved these changes

2022-09-21 17:58 UTC, thegreatercurve requested changes

2022-09-21 17:58 UTC, thegreatercurve commented on packages/lexical/src/nodes/LexicalTextNode.ts
> +  setDetail(detail: number): this {
This API has already been reported as confusing by users. Why should `toggleDetail` accept a string but `setDetail` accept a number?

2022-12-01 18:12 UTC, thegreatercurve approved these changes

2022-12-01 20:09 UTC, trueadm commented
I'm not super sold on this. The `__detail` property was never meant to be exposed really, it was used to store internal information only. Having a set/get for it is more confusing IMO.

I think set/get Format is a different thing entirely here too. That is meant to be exposed.

2022-12-01 21:00 UTC, trueadm requested changes
Let's rethink the __detail changes.

2022-12-06 13:38 UTC, trueadm approved these changes

2022-12-07 19:49 UTC, trueadm commented
Is this going in 0.7?

2023-02-06 10:39 UTC, thegreatercurve commented
Closing this due to PR becoming stale.

2023-02-06 10:39 UTC, closed without merging