Move default language setting to Tokenizer
facebook/lexical pull request #3368
Opened 2022-11-16 17:59 UTC by saint1991

### ~1. Add a preserve feature to CodeNode~

~In the original implementation, CodeNode is removed when the backward deletion occurs at the beginning of the Node.~
~In some use cases, implementing a code editor, such behavior is not needed.~
~The "Preserve" setting is for making it controllable.~

### 2. Move the default language setting to Tokenizer 

The former PR #3243 enabled to use arbitrary Tokenizer other than Prism and 'javascript' is not always appropriate to the default so make it a Tokenizer setting.

This PR contains 2 changes but I'm happy to divide them if required.

2022-11-17 11:05 UTC, saint1991 commented on packages/lexical-website/docs/demos/plugins/embeds/_category_.yml
> +position: 1
just apply pretteir

2022-11-20 00:26 UTC, saint1991 commented
I have no idea how to fix the failed e2e tests...
It seems to be occurring in the main branch randomly.

2022-11-25 17:08 UTC, thegreatercurve requested changes
@saint1991 The default language changes seems fine, but I think we'd want to leave out the preserve flag. Users can just implement this themselves by extending the CodeNode and overwriting the collapseAtStart method.

2022-11-28 15:09 UTC, saint1991 commented
@thegreatercurve 

Thanks for your kind review!
Thanks to #3367, the code something like below works as  I expected.

Thank you so much for the great work!
I've removed commit 1. which is no longer needed as you mentioned.

```


export class CodeEditorNode extends CodeNode {
  static getType(): string {
    return 'code-editor';
  }

  collapseAtStart(): true {
    return true;
  }
}

export const $createCodeEditorNode = (language?: string | null | undefined): CodeEditorNode => {
  return new CodeEditorNode(language);
}

const editor = createEditor({
  nodes: [
    CodeEditorNode,
    CodeNode: {
      replace: CodeNode, 
      with: (node: CodeNode) => $createCodeEditorNode(node.getLanguage())
    },
    CodeHighlightNode,
  ]
})
```

2022-11-29 11:28 UTC, thegreatercurve commented on packages/lexical-code/flow/LexicalCode.js.flow
> +declare export function $createCodeNode(language?: string | null): CodeNode;
This should just be enough:
```suggestion
declare export function $createCodeNode(language: ?string): CodeNode;
```

2022-12-01 14:05 UTC, thegreatercurve approved these changes

2022-12-02 15:47 UTC, fantactuka commented
I'm curious if it's better to have default language as a param to `registerCodeHighlighting` and `CodeHighlightingPlugin`. Then you can have single tokenizer but custom default language based on specific surface needs

2022-12-03 15:56 UTC, saint1991 commented
I think it's also OK, but I put the setting here because the supported languages depend on Tokenizer's implementation. The setting 'javascript' is one of the proper choices for PrismTokenizer because Prism supports it.

In terms of the use of the library, the difference is that users should specify the default language even when they use PrismTokenizer by default.

2022-12-08 19:24 UTC, merged