Exports serialized node types
facebook/lexical pull request #3436
Opened 2022-11-27 21:23 UTC by tolkienfan2

Exports serialized node types from main lexical package.

2022-11-27 21:59 UTC, tolkienfan2 commented
I really don't know why the test above is failing with the message Error: prettier exit code 1.
When I run npm prettier in my local branch, it runs without any errors.

2022-11-28 13:11 UTC, thegreatercurve requested changes
Thanks @tolkienfan2! Just one small change.

2022-11-28 13:11 UTC, thegreatercurve commented on packages/lexical/src/index.ts
> + } from './../../lexical-table/src';
This should generally be fine, but we don't want to re-export these from the core as it will just inflate the size of core for everyone. These should all be exported from the `index` files in their respective packages.

2022-11-28 13:36 UTC, tolkienfan2 commented on packages/lexical/src/index.ts
> + } from './../../lexical-table/src';
Oh, ok. So I should just close this PR in this case?

2022-11-28 18:49 UTC, thegreatercurve commented on packages/lexical/src/index.ts
> + } from './../../lexical-table/src';
No, just delete the above few lines and you should be fine.

2022-11-28 21:01 UTC, thegreatercurve approved these changes

2022-11-28 22:00 UTC, merged