Improve markdown transformers
facebook/lexical pull request #3886
Opened 2023-02-11 11:45 UTC by Godefroy

I need to import a markdown document with tables containing markdown in each cell.

Problem: `$convertFromMarkdownString` is currently not called inside of table cells and doesn't take a target node as a parameter, it uses root node only.

The `TABLE` transformer needs to be adapted, as well as `createMarkdownImport` (which is used by `$convertFromMarkdownString`) and `createMarkdownExport`.

This pull request adds:
- Markdown import inside table cells
- Markdown export inside table cells
- Table row header import
- Emoji import

You can test with this markdown example:
```md
| Table | Col 1 | Col 2 |
|-------|-------|-------|
| Line 1 | *Content* | Multi\nlines |
| Line 2 | Emoji :smile: | `Code` |
```

2023-02-13 02:53 UTC, acywatson requested changes
CI integrity is failing for some reason - looks like prettier

2023-02-13 02:53 UTC, acywatson commented on packages/lexical-playground/src/plugins/MarkdownTransformers/index.ts
> +import emojiList from '../EmojiPickerPlugin/emoji-list';
Plugins should be dependent directly on other plugins like this. You'd need to pull the common logic out to a shared dir somewhere.

2023-02-13 02:53 UTC, acywatson commented on packages/lexical-playground/src/plugins/MarkdownTransformers/index.ts
> +  if (!match || !match[1]) return null;
we typically don't do one line conditional like this (IIRC). Nothing against it personally, just a repo style consistency thing.

2023-02-13 02:53 UTC, acywatson commented on packages/lexical-markdown/src/index.ts
> +  createMarkdownExport,
@fantactuka is this what we want to do?

2023-02-19 16:53 UTC, Godefroy commented on packages/lexical-playground/src/plugins/MarkdownTransformers/index.ts
> +import emojiList from '../EmojiPickerPlugin/emoji-list';
I understand, but there are already 6 other plugins depending on other plugins like this, and plugins are tightly coupled with other folders (nodes, ui). I'm not sure how to make this change properly.

Do you have a preference between:

1. Moving `emoji-list.ts` in `utils` or another folder
2. Removing this commit to remove emojis transformer
3. Refactor playground transformers to set them from root component Editor to improve modularity.

2023-02-19 16:56 UTC, Godefroy commented on packages/lexical-markdown/src/index.ts
> +  createMarkdownExport,
The alternative is to adapt also `$convertToMarkdownString` and use it instead.

Should I do that?

2023-03-01 00:30 UTC, acywatson commented on packages/lexical-playground/src/plugins/MarkdownTransformers/index.ts
> +import emojiList from '../EmojiPickerPlugin/emoji-list';
@Godefroy You can just do the first one

2023-03-08 20:00 UTC, Godefroy commented
Thanks @acywatson for the code review! I adapted my code.

Also, I took the liberty to remove `root.selectEnd();` from `createMarkdownImport` because I think it's not its job and it was causing the equivalent of an autoFocus when importing a markdown.

2023-03-21 12:03 UTC, acywatson approved these changes

2023-03-21 12:03 UTC, acywatson commented on packages/lexical-playground/src/plugins/MarkdownTransformers/index.ts
> +    if (TABLE_ROW_DIVIDER_REG_EXP.test(match[0])) {
@zurfyx will this be a problem for the tables works you're currently doing? I doubt it, but wanted to check.

2023-03-21 12:03 UTC, acywatson commented on packages/lexical-playground/src/plugins/EmojiPickerPlugin/index.tsx
> +    import('../../utils/emoji-list.ts').then((file) => setEmojis(file.default));
thanks for this

2023-03-21 12:03 UTC, acywatson commented on packages/lexical-markdown/src/MarkdownImport.ts
> +): (markdownString: string, node?: ElementNode) => void {
I'm ok with this - maybe a nit to call it targetNode or something that indicates that it's the parent of whatever the import creates.

Separately, why shouldn't markdown work more like HTML, where you just get back some nodes and then insert them wherever you want?

@fantactuka 

I'm ok with this change.

2023-03-21 13:18 UTC, merged