Bugfix: ColorPicker color changing adds multiple entries in undo stack
facebook/lexical pull request #3984
Opened 2023-02-27 00:40 UTC by KhalfounMehdi

The bug is described in the following issue : #3890

2023-02-28 20:09 UTC, thegreatercurve commented
@KhalfounMehdi This generally looks fine! Would you mind just fixing the few lint errors?

2023-02-28 21:23 UTC, KhalfounMehdi commented
@thegreatercurve  actually i need to fix an bug that I noticed in my fix : 
- after I call the editor.update , the merge action returned is `HISTORY_MERGE` and it should be `HISTORY_PUSH`
I'll finish with the bug , I will fix the lining errors nad push

2023-03-03 16:19 UTC, thegreatercurve commented on packages/lexical-playground/src/ui/ColorPicker.tsx
> +  const HandleDropDownClose = React.useCallback(() => {
```suggestion
  const HandleDropDownClose = useCallback(() => {
```

2023-03-15 13:11 UTC, fantactuka commented on packages/lexical-playground/src/ui/DropDown.tsx
> +  function usePrevious(value: any) {
Unless we want this to be common util, you can just use ref without hook

2023-04-22 12:39 UTC, zurfyx requested changes
Can we please revise the behavior of this PR and consider replicating the mouse up behavior from Figma (suggested in https://github.com/facebook/lexical/issues/3890)? The ColorPicker doesn't seem to be working correctly and also breaks the same time you open the picker

https://user-images.githubusercontent.com/193447/233785218-040de80e-ea65-4aa3-880b-c04ab21f7509.mov

2023-05-31 21:32 UTC, thegreatercurve commented
Closing due to PR becoming stale

2023-05-31 21:32 UTC, closed without merging