Show floating link editor for autolinks
facebook/lexical pull request #4203
Opened 2023-03-25 17:25 UTC by AlessioGr

Fixes #4202 

I found it **really** confusing that the link editor menu did not show up for autolinks, to the point where I opened an issue thinking it was a bug. Apparently, this was intended, judging from the comment.

This PR makes the floating link editor show for autolinks too, as I think it's a bad UX if the link shows up as blue - looks exactly the same as normal links - but the floating link editor doesn't show up. I guess I wouldn't be the only one getting confused by this, thinking it's a bug.

2023-03-25 18:29 UTC, fantactuka commented
Looks good to me, could you check if auto link converted to regular link if url is updated? Since it does not make sense to keep it as autolink anymore

2023-03-25 19:38 UTC, AlessioGr commented
> Looks good to me, could you check if auto link converted to regular link if url is updated? Since it does not make sense to keep it as autolink anymore

Mh it's not converted currently / it stays as autolink. Is there an easy way to convert it?

2023-03-27 06:10 UTC, khanakia commented
With this change regular link toggle edit will stop working

2023-03-27 06:17 UTC, AlessioGr commented
> With this change regular link toggle edit will stop working

The regular link toggle still works for me - can you share a screen recording?

2023-03-27 06:44 UTC, khanakia commented
@AlessioGr yes it works now you can ignore previous comment

2023-04-22 12:43 UTC, zurfyx requested changes
(see comment above)

2023-04-30 11:20 UTC, AlessioGr commented
Thank you! Just wanna say I didn't abandon this PR - will work on converting the autolink into a normal link once I find time ^^

2023-09-22 19:31 UTC, zurfyx commented
Inactivity cleanup. Feel free to reopen a new PR!

2023-09-22 19:31 UTC, closed without merging