bug: fix code block lines #4361
facebook/lexical pull request #4375
Opened 2023-04-21 11:13 UTC by rajarshisamaddar

The Code block, which previously did not display line numbers until the very end, has been corrected in this pull request.

Closes #4361  Bug: code block lines

Testing instructions:
1. Install all the required packages from the package.json file.
2. Launch the Lexical Playground and evaluate the code block that now features horizontal scrolling with proper line numbering.

Additional notes:
- Please don't hesitate to bring up any additional steps needed to merge this pull request.
- Fixed ✅

![FB Lexical](https://user-images.githubusercontent.com/61039817/233621935-53bc0d2c-6779-4fc8-a7ea-c314a6bae780.jpg)

2023-04-21 16:31 UTC, affvalente commented
Empty lines seems fixed, but now text does not wrap

![image](https://user-images.githubusercontent.com/25633523/233688322-db94aa61-3f2c-47ef-9130-e348c90c8bc5.png)

2023-04-21 16:46 UTC, rajarshisamaddar commented
> Empty lines seems fixed, but now text does not wrap
> 
> ![image](https://user-images.githubusercontent.com/25633523/233688322-db94aa61-3f2c-47ef-9130-e348c90c8bc5.png)

Okay, I'll fix that

2023-04-22 05:50 UTC, rajarshisamaddar commented
> 

I decided to address this matter but later discovered that the majority of code or text editors do not permit users to move to the next line. Since this is a code block, the text appears as comments that cannot be split into multiple lines unless it is a multi-line comment.

To sum up, I believe the functionality is adequate when compared to other code editors. However, I would appreciate hearing your thoughts on this matter.

2023-04-22 05:50 UTC, rajarshisamaddar commented
> > 
> 
> I decided to address this matter but later discovered that the majority of code or text editors do not permit users to move to the next line. Since this is a code block, the text appears as comments that cannot be split into multiple lines unless it is a multi-line comment.
> 
> To sum up, I believe the functionality is adequate when compared to other code editors. However, I would appreciate hearing your thoughts on this matter.

2023-04-22 06:01 UTC, affvalente commented
The current editor wraps the text so I don't think we should reverse that functionality. 

The wrap should be just a visual thing. With a long enough screen a very long line should be line #1. 

On a small screen, it should still be #1 as well even if visually it takes 4-5 wrapped lines. These wrapped lines have no line number in the data gutter

This seems to be an issue with how the line numbering in the data-gutter element is done, rather than the CSS.

2023-04-22 06:19 UTC, rajarshisamaddar commented
> Edit: what you describe seems consistent with how GitHub shows code. Perhaps we need an horizontal scrollbar

I'll add a horizontal scroll bar, anything else?

2023-04-22 08:57 UTC, affvalente commented
Up to the team - I'm just a user!

2023-04-22 13:06 UTC, rajarshisamaddar commented
@acywatson Would you mind reviewing this pull request, please?

2023-04-22 16:12 UTC, acywatson approved these changes
Yea this looks right to me. Thanks!

2023-04-22 16:36 UTC, rajarshisamaddar commented
> Yea this looks right to me. Thanks!

Hi @acywatson, you're welcome. Could you please merge this request, if possible?

2023-04-22 21:14 UTC, acywatson commented
> > Yea this looks right to me. Thanks!
> 
> Hi @acywatson, you're welcome. Could you please merge this request, if possible?

I'm actually second guessing this now - give me some time to think about this. Thank you

2023-04-23 05:27 UTC, rajarshisamaddar commented
> > > Yea this looks right to me. Thanks!
> > 
> > 
> > Hi @acywatson, you're welcome. Could you please merge this request, if possible?
> 
> I'm actually second guessing this now - give me some time to think about this. Thank you

Certainly! Take your time to think things through and let me know if you have any questions or if there's anything else I can help you with.

2023-04-25 17:48 UTC, zignis commented
Adding nowrap defeats the entire purpose, imo, as it will force horizontal scrollbars unless you hide the overflow, which is not desirable. The current need is to fix the line numbers while allowing the code to wrap.

2023-05-01 18:10 UTC, zurfyx requested changes
Thank you for taking a stab on this! While I think that this your proposal is a valid, in fact, that's how VSCode works by default until you do Option + Z, I think it's worth exploring the root cause of the issue as @zignis pointed out. Then, users, on their editors, can choose whether to wrap.

2023-06-19 12:32 UTC, thegreatercurve commented
Closing due to inactivity, but happy to re-open if comments above can be addressed.

2023-06-19 12:32 UTC, closed without merging