Add TableCell writingMode #4437
facebook/lexical pull request #4438
Opened 2023-05-01 11:23 UTC by IBastawisi

2023-05-01 15:10 UTC, zurfyx requested changes
Thank you! Let me start by saying that this is a nice feature so thank you for working on this

2023-05-01 15:10 UTC, zurfyx commented on packages/lexical-table/src/LexicalTableCellNode.ts
> +    cellNode.__writingMode = node.__writingMode;
In retrospective, having a `__backgroundColor` property isn't great. That was my bad, for some reason I thought that cells would never need any more styling properties and that they could be done on child nodes.

Can we copy TextNode `getStyle()`? Maybe the caching part isn't too critical for now but the property is important.

The reason why we have to do this before we merge your PR is backward compatibility. Once we commit to supporting this prop it will be hard to roll it back.

The second (minor) is because we probably don't want to commit on it officially until we address the overflow-x issue somehow:

<img width="449" alt="Screenshot 2023-05-01 at 10 57 45 AM" src="https://user-images.githubusercontent.com/193447/235474019-e7e174c8-b111-483a-b695-7147d4163f3d.png">

2023-05-01 21:55 UTC, IBastawisi commented on packages/lexical-table/src/LexicalTableCellNode.ts
> +    cellNode.__writingMode = node.__writingMode;
I agree that all CSS styles should go in one node property.
regarding the overflow issue we can hide the table cell overflow and also inherit the tr height to allow cell resizing:
```css
.PlaygroundEditorTheme__tableCell {
    height: inherit;
    overflow: hidden;
}
```
I might give it a try soon.

2023-05-04 10:33 UTC, IBastawisi commented
The previous commit breaks Cell background color feature disabled test which is expected.
should we deprecate the backgroundColor property or drop it altogether?

2023-05-04 10:38 UTC, IBastawisi commented
oh the serialized style property is breaking some unit tests as well, my bad!
![image](https://user-images.githubusercontent.com/13211445/236181067-7798ff58-8b06-4c33-a960-b10e0782b3b7.png)

2023-07-15 15:29 UTC, closed without merging