Allow arbitrary awareness fields in Collaboration plugin
facebook/lexical pull request #4507
Opened 2023-05-17 11:30 UTC by attnov

### Summary
This change allows arbitrary data (for example 3rd party UUID) to be added to awareness. Right now user name and color is hard coded in Collaboration plugin. The new parameter `awarenessData` is optional.

### Usage example
We can specify our arbitrary data like this:
```
const awarenessData = {
  uuid: 42,
  foo: 'bar',
);
```

With the new parameter, we can send down our arbitrary data:
```
<CollaborationPlugin
  id="id"
  providerFactory={providerFactory}
  shouldBootstrap={shouldBootstrap}
  awarenessData={awarenessData}
/>
```

2023-05-17 23:52 UTC, ivailop7 approved these changes
Thank you, Attila. @acywatson and @zurfyx . Could you give it a look as well.

2023-05-18 13:11 UTC, fantactuka commented
I don't think works since map is not json serializeable, should be plain object like remaining of awareness data. Personal opinion: naming looks a bit odd, as usage will be awareness.getLocalState().awarenessFields, maybe data or extraData would do better, no strong opinion tho

2023-05-18 13:24 UTC, fantactuka requested changes
~

2023-05-18 17:53 UTC, fantactuka commented on packages/lexical-react/src/__tests__/unit/Collaboration.test.ts
> +    );
Could you use awareness.getStates() instead, to ensure that client1 has proper awareness from client2 and vise versa?

2023-05-18 17:53 UTC, fantactuka commented on packages/lexical-react/src/shared/useYjsCollaboration.tsx
> +  awarenessFields?: object,
I wonder if we can use `{ ... }` here and remove eslint comment above

2023-05-18 17:55 UTC, fantactuka commented
Thanks for updates! 

@acywatson @zurfyx thoughts on naming?

2023-05-18 18:07 UTC, acywatson commented
> Thanks for updates!
> 
> @acywatson @zurfyx thoughts on naming?

I like having awareness in the name, but fields is probably wrong. "awarenessData" or "extraAwaresnessData" seems fine.

doc block on the interface would help people know what it's for.

2023-05-19 11:37 UTC, attnov commented on packages/lexical-react/src/shared/useYjsCollaboration.tsx
> +  awarenessFields?: object,
Actually, we don't need the eslint comments anymore - `any` is not used anymore. Removed all of them.

2023-05-19 11:38 UTC, attnov commented
> > Thanks for updates!
> > @acywatson @zurfyx thoughts on naming?
> 
> I like having awareness in the name, but fields is probably wrong. "awarenessData" or "extraAwaresnessData" seems fine.
> 
> doc block on the interface would help people know what it's for.

Renamed the parameter to `awarenessData` and added documentation on the inferface.

2023-05-19 11:40 UTC, attnov commented on packages/lexical-react/src/__tests__/unit/Collaboration.test.ts
> +    );
It looks like [here ](https://github.com/facebook/lexical/blob/main/packages/lexical-react/src/__tests__/unit/utils.tsx#L94)the mock for getStates() only inserts the current client's awareness state.

2023-05-19 13:27 UTC, zurfyx approved these changes

2023-05-19 13:27 UTC, zurfyx commented on packages/lexical-react/src/__tests__/unit/utils.tsx
> +    getLocalState(): any;
Can we make this better? Besides the `object` prop what other types we don't know?

2023-05-19 14:05 UTC, attnov commented on packages/lexical-react/src/__tests__/unit/utils.tsx
> +    getLocalState(): any;
I have added types for getLocalState(), getStates(), setLocalState(), etc.
Thanks for checking!

2023-05-19 14:41 UTC, fantactuka commented on packages/lexical-yjs/src/index.ts
> +    awarenessData: awarenessData,
```suggestion
   awarenessData,
```

Similar one below

2023-05-19 14:41 UTC, fantactuka approved these changes

2023-05-19 15:43 UTC, merged