fix: check pure text by regex (without emojis)
facebook/lexical pull request #5269
Opened 2023-11-22 10:35 UTC by tasadophi

This pr related to this [issue](https://github.com/facebook/lexical/issues/5260). The regex was wrong and return rtl when any emoji was in the text. I added an extra regex to replace emojis with empty string then main regex check the pure text and return real direction

2023-12-15 08:02 UTC, tasadophi commented
This bug occurs when write emoji and after that is rtl text and editor make whole text ltr @fantactuka @zurfyx @acywatson

2023-12-30 17:30 UTC, tasadophi commented
@fantactuka @zurfyx @acywatson Hi, good job I fixed this issue and pass tests now. You make a lot of users happy by fix this bug

2024-01-17 22:35 UTC, zurfyx requested changes
Thank you for fixing this, that's a good one! Added a comment

2024-01-17 22:35 UTC, zurfyx commented on packages/lexical/src/LexicalUtils.ts
> +      .trim();
While this is correct, this might hit performance hard, let's rework this regex. You want a Regex that starts with `^` and looks up at most a O(1) number of characters. Spacing might be a bit of an edge case here since it can be up to O(n) but at the same time it's rare to have them at the start of the text.

In fact, I would say that you can bundle this Regex with the LTR and RTL regexes so that you have something like `^(skipSpacesAndEmojis)LTR or RTL`

I would also move it outside of this function so that it's compiled once.

2024-01-18 15:53 UTC, tasadophi commented on packages/lexical/src/LexicalUtils.ts
> +      .trim();
Yes, everything in programming world can be better and better. could you please do this changes? Because Im not perfect in regex and its performance problems. Just I found this bug and I wanted help to lexical devs and say thanks to them that make our works easy !

2024-11-11 10:04 UTC, potatowagon commented
Closing this PR due to staleness! If there are new updates, please reopen the PR.

2024-11-11 10:04 UTC, closed without merging