keep selection style when clicking empty editor
facebook/lexical pull request #5292
Opened 2023-11-27 16:41 UTC by youngkyo0504

resolve #5202 

change code to keep selection style when clicking editor which has empty content.

`before`

https://github.com/facebook/lexical/assets/78121870/c2198c28-e190-4efe-886c-03ed20e4be80

`after`

https://github.com/facebook/lexical/assets/78121870/01f0deb7-5b65-4e01-b77a-cdaf16a85bc1

2023-11-27 17:14 UTC, ivailop7 commented
@youngkyo0504 can you sign the CLA and I'm OK with merging this.

2023-11-28 00:07 UTC, youngkyo0504 commented
> @youngkyo0504 can you sign the CLA and I'm OK with merging this.

Thank you! I have signed the CLA 😁

2023-11-28 00:10 UTC, acywatson requested changes

2023-11-28 00:10 UTC, acywatson commented on packages/lexical/src/LexicalEvents.ts
> +import {$isRootTextContentEmpty} from '@lexical/text';
I don't think we should create this dependency between the core and @lexical/text

2023-11-28 00:52 UTC, youngkyo0504 commented on packages/lexical/src/LexicalEvents.ts
> +import {$isRootTextContentEmpty} from '@lexical/text';
@acywatson 

how about using this instead of delete dependency? 

```ts
const root = $getRoot();
isRootEmpty  root.getTextContent() === ''
```

2023-12-04 14:54 UTC, acywatson approved these changes

2023-12-04 17:06 UTC, merged