Refactor classname splitting from `' '` to `/\s+/`
facebook/lexical pull request #5327
Opened 2023-12-03 19:09 UTC by sakib412

2023-12-04 14:43 UTC, zurfyx reviewed
Thanks, any real life example when this is needed?

2023-12-04 14:51 UTC, sakib412 commented
> Thanks, any real life example when this is needed?

https://discord.com/channels/953974421008293909/1180070470935117884/1180070470935117884

<img width="720" alt="image" src="https://github.com/facebook/lexical/assets/54371956/18c0ba51-ebb9-4b78-a717-1df8681d574a">

2023-12-04 14:52 UTC, acywatson commented
> Thanks, any real life example when this is needed?

Yea if you have more than one space between classnames, the original implementation will fail. There's a thread about it on Discord.

2023-12-06 06:43 UTC, sakib412 commented
> Almost feels like this could be extracted out to a util so we don't risk inconsistent class splitting logic in different places.

I have added a util function and testing

2023-12-07 03:47 UTC, acywatson requested changes

2023-12-07 03:47 UTC, acywatson commented on packages/lexical/src/LexicalUtils.ts
> +import {splitClasses} from '@lexical/utils';
Thanks for making this change. However, we don't want the core to have any dependencies, including on other lexical packages, like @lexical/utils.

This means split classes needs to live in the core if it's used there, unfortunately.

2024-01-18 20:44 UTC, zurfyx commented
Inactivity cleanup. Feel free to reopen

2024-01-18 20:44 UTC, closed without merging