[PR-5] Remove references of PointSelection
facebook/lexical pull request #5334
Opened 2023-12-05 15:06 UTC by icrosil

## Why
In #5276  we proposed a solution on how to migrate GridSelection out of the core of the bundle, here is the fourth step by removing GridSelection into lexical-table package.

## What
Removed all intermediate references of PointSelection.

2023-12-15 15:26 UTC, icrosil commented
@zurfyx, @fantactuka if you are still around do you mind reviewing this last piece?

2023-12-15 16:53 UTC, acywatson approved these changes

2023-12-15 18:42 UTC, zurfyx requested changes
Thanks, great work, this is a complicated PR, added some comments.

Couple of opinionated Lexical syntax stuff we do here:
- Prefer `===` to `==`
- Prefer `null | X` over `X | null`

Also, don't forget to run `npm run extract-codes` if you change invariants

2023-12-15 18:42 UTC, zurfyx commented on packages/lexical-list/src/formatList.ts
> +    if (selection != null) {
```suggestion
    if (selection !== null) {
```

2023-12-15 18:42 UTC, zurfyx commented on packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
> +        if (selection != null) {
```suggestion
        if (selection !== null) {
```

2023-12-15 18:42 UTC, zurfyx commented on packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
> +        if (selection != null) {
```suggestion
        if (selection !== null) {
```

2023-12-15 18:42 UTC, zurfyx commented on packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx
> +        if (selection != null) {
```suggestion
        if (selection !== null) {
```

2023-12-15 18:42 UTC, zurfyx commented on packages/lexical-selection/src/lexical-node.ts
> +  selection: BaseSelection,
Shouldn't this be RangeSelection? Once you get rid of GridSelection here you will have a similar problem and having the function do nothing is not a great behavior. How are you thinking about Grid?

2023-12-15 18:42 UTC, zurfyx commented on packages/lexical/src/LexicalSelection.ts
> +  const [anchor, focus] = selection.getStartEndPoints();
I'd be keen to leave the previous version, in this one you're constructing and deconstructing an array unnecessarily. Won't make a difference performance wise but I think the previous version was fine

Or you can change it to `const {anchor, focus} = ..`

2023-12-15 18:42 UTC, zurfyx commented on packages/lexical-selection/src/range-selection.ts
> +  if ($isNodeSelection(selection) || anchor == null || focus == null) {
I think we can wrap NodeSelection nodes just fine? I'd say either we implement it or we make the signature more strict

2023-12-15 18:42 UTC, zurfyx commented on packages/lexical-selection/src/range-selection.ts
> +  }
I think we can implement it for NodeSelection? I'd say either we implement it or we make the signature more strict

2023-12-15 18:42 UTC, zurfyx commented on packages/lexical-rich-text/src/index.ts
> -          if ($INTERNAL_isPointSelection(selection)) {
I wonder if we can remove this, because this hardcoded function will be very hard to override by anyone else who does custom selection, but we can revisit later

2023-12-15 18:42 UTC, zurfyx commented on packages/lexical-rich-text/src/index.ts
> +      if (clipboardData != null && selection != null) {
Can you give more details on the reasoning here? This is not the same as the condition on the left

2023-12-18 11:36 UTC, icrosil commented on packages/lexical-selection/src/lexical-node.ts
> +  selection: BaseSelection,
Right now this function performs as single function to patch styles for any selection
Node -> noop
Range -> do
Not Range (technically Grid) -> create Range

personally I think we should leave it like this unless we want to get rid of all functions like this from the code, but that would be a great deal of refactoring.

2023-12-18 11:44 UTC, icrosil commented on packages/lexical/src/LexicalSelection.ts
> +  const [anchor, focus] = selection.getStartEndPoints();
the problem here and reason why we need this new function is that Lexical usually tries to get anchors/focus from BaseSelection - like here and it could be nulls for NodeSelection, but proper in Range or Grid. So basically we had 2 ways of dealing with them:

make new class to get specialized types - PointSelection which we decided to get rid of.
or put some sort of anchor/focus knowledge in baseSelection - getStartEndPoints.

it's also similar to problem above because functions we cannot specify type and have to work backwards from BaseSelection, which seems like best approach here if we are allowing Selections to be created by users or package specific selections like Grid.

2023-12-18 11:47 UTC, icrosil commented on packages/lexical-selection/src/range-selection.ts
> +  if ($isNodeSelection(selection) || anchor == null || focus == null) {
ooh this is a good spot!

2023-12-18 11:56 UTC, icrosil commented on packages/lexical-rich-text/src/index.ts
> +      if (clipboardData != null && selection != null) {
yeah so now clipboard data will try to insert text on NodeSelection too that I thought should be alright or caught by tests. But what we can do - check if selection is node and not allow it, wdyt?

2023-12-18 11:59 UTC, icrosil commented
Hey @zurfyx I've resolved most of the feedback and left comments for other.

2023-12-18 17:03 UTC, ivailop7 approved these changes
Great effort!

2024-01-17 18:18 UTC, icrosil commented
Hey @zurfyx I've updated the patchStyle that we discussed offline, changes - I was able to remove !isNodeSelection and !isRangeSelection parts, returning early if no anchor/focus and treating GridSelection same as Range, that was already working with 1 simple change.

Will update more if CI is red, please let me know if there is anything else you'd like to revisit.

2024-01-17 21:30 UTC, zurfyx reviewed
Thanks for iterating on this! Added some comments (mostly minor stuff)

Also, you may want to check on why the playground errors upon click
![Screenshot 2024-01-17 at 4 29 34 PM](https://github.com/facebook/lexical/assets/193447/573988d5-f99c-466e-b803-842ebf58cc3a)

2024-01-17 21:30 UTC, zurfyx commented on packages/lexical-selection/src/lexical-node.ts
>    const selectedNodes = selection.getNodes();
`getNodes` will not capture all nodes except for RangeSelection, do we need to traverse them all to find at least all the TextNodes? We can exclude RangeSelection for the sake of performance.

I can help with this but let's at least document this in an issue and leave the GridSelection logic around so that we don't regress

2024-01-18 11:04 UTC, icrosil commented on packages/lexical-selection/src/lexical-node.ts
>    const selectedNodes = selection.getNodes();
So the only question here is how current method works for GridSelection, because NodeSelection is noop and RangeSelection works as expected.

I found that current patchStyle is actually working almost out of the box for Grid too. Here is how:

let's take in consideration 2 cases how GridSelection could be potentially involved:
- text selected inside of grid cell - A
- text selected across many grid cells - B

in case A - that's pure RangeSelection, which already will work as expected. For case B - we can safely assume that  we don't have case where not all grid cell is selected, because when we expand selection beyond 1 cell - it will set selection level for cells only. in this case GridSelection will have anchor -> cell start, focus -> cell end. Both elements would include all text inside without offsets.

Given that we need to make sure that pathStyle would work for case B. in the PR I've updated some logic in the end to make sure we are highlighting all cells, but answering your question:
getNodes will return Grid, Row, Cell, Paragraph and Text nodes (all of them) and current styling mechanism already filtering and applying style only to text blocks.

PS and only at this point I read your edit saying its alright xD

2024-01-18 18:57 UTC, zurfyx approved these changes
Thank you for iterating on this 🙏

2024-01-18 19:45 UTC, merged