Add support for grid selection in text alignment.
facebook/lexical pull request #5652
Opened 2024-02-23 05:45 UTC by serey-roth

The added support allows text alignment across multiple cells simultaneously by selecting those cells. Fixes #5638.

Before:

[before-text-alignment.webm](https://github.com/facebook/lexical/assets/88986106/74ee321e-b55e-4834-aa7d-0bc9613055c9)

After:

[after-text-alignment.webm](https://github.com/facebook/lexical/assets/88986106/629324cb-4619-4b35-af7a-bb9c6a05a6ff)

2024-02-23 21:11 UTC, ivailop7 commented on packages/lexical-rich-text/src/index.ts
> +          DEPRECATED_$isGridSelection(selection);
I believe you should be using isTableSelection, but @zurfyx should be able to confirm.

2024-02-24 05:59 UTC, serey-roth commented on packages/lexical-rich-text/src/index.ts
> +          DEPRECATED_$isGridSelection(selection);
Updated!

2024-02-25 21:25 UTC, ivailop7 commented on packages/lexical-rich-text/src/index.ts
> +        if (!validSelection) {
This is not the right approach to fix this, because it couples the 'rich-text' package to the 'tables' package, because of the isTableSelection import. The way to fix this correctly is to register FORMAT_ELEMENT_COMMAND inside the table plugin (LexicalTableSelectionHelpers.ts), similar to: https://github.com/facebook/lexical/blob/main/packages/lexical-table/src/LexicalTableSelectionHelpers.ts#L339-L369

2024-02-25 22:43 UTC, serey-roth commented on packages/lexical-table/src/LexicalTableSelectionHelpers.ts
> +    ),
@ivailop7 I'm transforming the selection to a `RangeSelection` and let the command in https://github.com/facebook/lexical/blob/69754ac50d5e025daacc35cd0cd79a50e76a3ab6/packages/lexical-rich-text/src/index.ts#L631-L651 handles the rest. I've found this to be a better solution than duplicating the existing format command. What are your thoughts?

2024-03-01 17:53 UTC, ivailop7 approved these changes
LGTM, could @zurfyx , @acywatson or @fantactuka have a look as well.

2024-03-03 16:22 UTC, zurfyx requested changes
Thank you for taking a stab at this! Added a comment

2024-03-03 16:22 UTC, zurfyx commented on packages/lexical-table/src/LexicalTableSelectionHelpers.ts
> +    ),
1. While it works for this particular case, the selection you've expressed above is not valid. Table selection can't be directly converted to a RangeSelection. Both anchor and focus are ElementNodes so their offset is unlikely to be 0. Similarly, you can't have a selection that goes from inside a ShadowRoot to another ShadowRoot.
2. A RangeSelection is linear and traverses the TreeNodes in order. Notice that table selection is a visually "rectangular" selection. For this reason, your implementation may target nodes that are not even selection, see video below.
3. For best UX, we want to restore selection to the previous value.

https://github.com/facebook/lexical/assets/193447/3ee92660-a955-4385-8a5b-76aca02c534f

For 2, you can leverage  `$computeTableMap` to extract all the (relevant) table cells.

2024-03-03 23:05 UTC, serey-roth commented on packages/lexical-table/src/LexicalTableSelectionHelpers.ts
> +                child.setFormat(formatType);
https://www.loom.com/share/9bacba8043234c5f8013652d5c010573?sid=3f6684e5-201d-43d9-9c65-035a1370d439

2024-03-04 15:19 UTC, zurfyx commented on packages/lexical-table/src/LexicalTableSelectionHelpers.ts
> +                child.setFormat(formatType);
@serey-roth - Yes, that looks like another bug. In fact, I'd expect that pressing Enter on a centered paragraph would center the next one.

2024-03-04 15:22 UTC, zurfyx submitted a review, later dismissed
LGTM, thanks for iterating on this! Do you mind writing an E2E test for it please?

2024-03-04 20:28 UTC, zurfyx approved these changes
Thank you!

2024-03-04 20:28 UTC, merged