docs: add a tip about discrete state update
facebook/lexical pull request #5664
Opened 2024-02-28 14:32 UTC by Dzieni

Fixes #5660 

Also, I think it might be reasonable to copy/adapt the [discrete update section of @DaniGuardiola's article](https://dio.la/article/lexical-state-updates#discrete-updates) into the docs. Applying `discrete: true` sounds like a common use case in a headless context.

2024-02-28 17:13 UTC, acywatson requested changes

2024-02-28 17:13 UTC, acywatson commented on packages/lexical-website/docs/concepts/serialization.md
> +Remember that state updates are asynchronous, so executing `editor.getEditorState()` immediately afterwards might not return the expected content. To avoid it, [pass `discrete: true` in the `editor.u
Thanks for this PR!

While I do think it's good to mention the "discrete" tag, I don't want to encourage people to do this. In most cases, people should just be using the standard listener pattern to interact with the state. I think leaning on discrete too heavily can encourage inefficient patterns.

My suggestion here is to also include the consequences of adding the discrete tag, one of which is that the update won't be batched, which can lead to unnecessary update cycles.

Another suggestion would be to add a new section about tags in the "update" section of the docs, because this is really not an issue specific to serialization.

2024-02-28 19:19 UTC, Dzieni commented on packages/lexical-website/docs/concepts/serialization.md
> +Remember that state updates are asynchronous, so executing `editor.getEditorState()` immediately afterwards might not return the expected content. To avoid it, [pass `discrete: true` in the `editor.u
@acywatson Just to be clear - is there a better way than `discrete: true` to solve the problem mentioned in #5660? Maybe `htmlToLexical` should return a promise that gets resolved by the editor update listener?

2024-02-28 22:10 UTC, acywatson commented on packages/lexical-website/docs/concepts/serialization.md
> +Remember that state updates are asynchronous, so executing `editor.getEditorState()` immediately afterwards might not return the expected content. To avoid it, [pass `discrete: true` in the `editor.u
> @acywatson Just to be clear - is there a better way than discrete: true to solve the problem mentioned in https://github.com/facebook/lexical/issues/5660? Maybe htmlToLexical should return a promise that gets resolved by the editor update listener?

Ah, I see - I didn't actually look at the issue - I'm sorry about that.

So, yes: discrete is one option here. Another option is to pass an onUpdate callback:

```
editor.update(() => {

}, {
  onUpdate: () => {  editor.getEditorState().read(() => {})... }
})
```

I think your change is fine, then. You can also add something about onUpdate, if you want.

2024-02-28 22:11 UTC, acywatson approved these changes

2024-02-29 09:24 UTC, Dzieni commented on packages/lexical-website/docs/concepts/serialization.md
> +Remember that state updates are asynchronous, so executing `editor.getEditorState()` immediately afterwards might not return the expected content. To avoid it, [pass `discrete: true` in the `editor.u
OK, I think I'll add a few words in the "Updating state" chapter about possible waits to await the update.

2024-03-01 19:34 UTC, acywatson commented
I'll merge this for now, please feel free to add the additional docs later.

2024-03-01 19:34 UTC, merged