Improve table selection and navigation.
facebook/lexical pull request #5767
Opened 2024-03-26 16:33 UTC by serey-roth

This PR addresses several issues related to table selection and navigation within the editor. The following changes have been made:

- Pressing the left arrow key to exit the first cell moves selection to the previous sibling node, if exists.

https://www.loom.com/share/f16a323757294da7b767ba870fa18421?sid=e7ee42d6-2e59-4ffb-87db-00d8fed838d8

- Pressing the right arrow key to exit the last cell moves selection to the next sibling node, if exists.
- Pressing the left arrow key at the start of a paragraph under the table moves selection to the last cell of the table. (Fix #5627)
- Pressing the `Enter` key, when the cursor is before the table on the same line, moves selection to a new preceding paragraph.
- Pressing the `Enter` key, when the cursor is after the table on the same line, moves selection to the next paragraph (if exists), or otherwise,  a new paragraph. (Fix #5627)

2024-03-26 17:40 UTC, ivailop7 commented on packages/lexical-table/src/LexicalTableSelectionHelpers.ts
> +    if (direction === 'backward' || direction === 'forward') {
I think this if statement becomes redundant, since it's always true? Unless there's another value for direction I'm unaware of.

2024-03-26 17:46 UTC, serey-roth commented
> This looks VERY VERY good, there's still a small bug related to what you are fixing, if you put your cursor on the line after the table, when you press Enter, it goes to the next row correctly now, but if you type 'abc' it doesn't go to the line below, but to the last cell in the table and puts the 'abc' in there.

This happens because the selection is still in the last cell of the table and the table is the last node. In this scenario, should we create a new paragraph and insert the text there? In my opinion, this is the most sensible solution since the cursor is technically outside. @ivailop7 What do you think?

2024-03-26 17:48 UTC, serey-roth commented on packages/lexical-table/src/LexicalTableSelectionHelpers.ts
> +    if (direction === 'backward' || direction === 'forward') {
The `$handleArrowKey` is called for every arrow key event.

2024-03-26 17:53 UTC, ivailop7 commented
> > This looks VERY VERY good, there's still a small bug related to what you are fixing, if you put your cursor on the line after the table, when you press Enter, it goes to the next row correctly now, but if you type 'abc' it doesn't go to the line below, but to the last cell in the table and puts the 'abc' in there.
> 
> This happens because the selection is still in the last cell of the table and the table is the last node. In this scenario, should we create a new paragraph and insert the text there? I think this is the most sensible solution since the cursor is technically outside. @ivailop7 What do you think?

Yes, I think this is the most sensible approach. Looking at how other editors behaves for this, they don't even allow the cursor to be on the same line as the table, but move it to a paragraph below the table directly when you click after the row after the table. So let's go with the same. Add a paragraph below and type in there.

2024-03-26 19:01 UTC, serey-roth commented
> > > This looks VERY VERY good, there's still a small bug related to what you are fixing, if you put your cursor on the line after the table, when you press Enter, it goes to the next row correctly now, but if you type 'abc' it doesn't go to the line below, but to the last cell in the table and puts the 'abc' in there.
> > 
> > 
> > This happens because the selection is still in the last cell of the table and the table is the last node. In this scenario, should we create a new paragraph and insert the text there? I think this is the most sensible solution since the cursor is technically outside. @ivailop7 What do you think?
> 
> Yes, I think this is the most sensible approach. Looking at how other editors behave for this, they don't even allow the cursor to be on the same line as the table, but move it to a paragraph below the table directly when you click after the row after the table. So let's go with the same. Add a paragraph below and type in there.

@ivailop7 Currently, the cursor will be on the same line as the table if you click on the table's right edge. Do we want to remove this as well? In that case, clicking outside the table, regardless of the click position, will move the selection to the next line.

2024-03-26 19:39 UTC, ivailop7 commented
Let's keep it for now next to the table and upon typing to append the paragraph below and have the text there. If we need to change it later, should be easy.

2024-03-27 16:48 UTC, serey-roth commented
> Let's keep it for now next to the table and upon typing to append the paragraph below and have the text there. If we need to change it later, should be easy.

@ivailop7 I've added this, but it only works when the table doesn't have a nested table as the last child in the last cell. I've noticed it's because of the selection; the cursor will still be on the last cell of the nested table when it appears to be on the same line as the outer table (see video below).

https://www.loom.com/share/3c655aead08e4286a7d3f6646a3c2498?sid=aadcfb4e-897f-4c8c-9d83-0d4c5e6276df

2024-03-27 16:50 UTC, ivailop7 commented on packages/lexical-table/src/LexicalTableSelectionHelpers.ts
> +    if (direction === 'backward' || direction === 'forward') {
Got it, thank you!

2024-03-27 16:58 UTC, ivailop7 commented
> > Let's keep it for now next to the table and upon typing to append the paragraph below and have the text there. If we need to change it later, should be easy.
> 
> @ivailop7 I've added this, but it only works when the table doesn't have a nested table as the last child in the last cell. I've noticed it's because of the selection; the cursor will still be on the last cell of the nested table when it appears to be on the same line as the outer table (see video below). The same thing happens when pressing the "Enter" key.
> 
> https://www.loom.com/share/3c655aead08e4286a7d3f6646a3c2498?sid=aadcfb4e-897f-4c8c-9d83-0d4c5e6276df

The nested tables strike again... to be honest I'm fine with this limitation, since it's still miles better than what we had before. Random speculation, but maybe a check if the parent node is TableCellNode could be a way to become aware of the nested tables and behave accordingly. Either way, happy with the direction!

2024-03-27 16:58 UTC, ivailop7 commented
Once you are happy with it, would you mind adding tests :)

2024-03-27 17:01 UTC, serey-roth commented
> Once you are happy with it, would you mind adding tests :)

Will do! As you noticed, I didn't include the ability to insert a new paragraph by clicking under the last row of the table. I'll tackle this on later, but I'm thinking it should only work for the outermost table? @ivailop7 What do you think?

2024-03-27 18:14 UTC, ivailop7 commented
Doing this after this PR should be fine! 👍🏻

2024-03-28 11:33 UTC, ivailop7 commented
@serey-roth one of your own tests is failing, once ready, will get the others to have a look at the PR too.

2024-03-28 16:59 UTC, serey-roth commented
> @serey-roth one of your own tests is failing, once ready, will get the others to have a look at the PR too.

The tests are failing in collab mode. I've noticed that no paragraphs are inserted along with the table, which ends up changing the selection path. @ivailop7  Is this the correct behavior?

2024-03-28 17:32 UTC, ivailop7 commented
> > @serey-roth one of your own tests is failing, once ready, will get the others to have a look at the PR too.
> 
> The tests are failing in collab mode. I've noticed that no paragraphs are inserted along with the table, which ends up changing the selection path. @ivailop7 Is this the correct behavior?

Not sure I get this one. Is this an issue that happens only when in collab, but fine in standalone? When you say no paragraph are inserted with the table, do you mean, a paragraph after the table upon 'table insert' or something else?

2024-03-28 19:15 UTC, serey-roth commented
> > > @serey-roth one of your own tests is failing, once ready, will get the others to have a look at the PR too.
> > 
> > 
> > The tests are failing in collab mode. I've noticed that no paragraphs are inserted along with the table, which ends up changing the selection path. @ivailop7 Is this the correct behavior?
> 
> Not sure I get this one. Is this an issue that happens only when in collab, but fine in standalone? When you say no paragraph are inserted with the table, do you mean, a paragraph after the table upon 'table insert' or something else?

It only happens in collab, and only when you insert the table via the dropdown after the initial load. Currently, it looks like we don't automatically insert a paragraph after editor loads. This causes the selection to be null. (See video below)

https://www.loom.com/share/6990dd65bb4c4f83876444ebf23e7f8e

https://www.loom.com/share/bf61832280834c8799e63887c8231573?sid=f7ffca54-d2da-4b29-afa2-ec5a3d55b404

2024-03-29 21:08 UTC, ivailop7 commented
> > > > @serey-roth one of your own tests is failing, once ready, will get the others to have a look at the PR too.
> > > 
> > > 
> > > The tests are failing in collab mode. I've noticed that no paragraphs are inserted along with the table, which ends up changing the selection path. @ivailop7 Is this the correct behavior?
> > 
> > 
> > Not sure I get this one. Is this an issue that happens only when in collab, but fine in standalone? When you say no paragraph are inserted with the table, do you mean, a paragraph after the table upon 'table insert' or something else?
> 
> @ivailop7 It only happens in collab, and only when you insert the table via the dropdown after the initial load. Currently, it looks like we don't automatically insert a paragraph after editor loads. This causes the selection to be null. (See videos below)
> 
> https://www.loom.com/share/6990dd65bb4c4f83876444ebf23e7f8e
> 
> https://www.loom.com/share/bf61832280834c8799e63887c8231573?sid=f7ffca54-d2da-4b29-afa2-ec5a3d55b404

This is interesting, didn't realize the difference in behaviour that the default paragraph is not insert when in collab, which makes sense. I do still find the failures strange, since other test would be affected. In this case, try just insert a paragraph after focusing the editor so that you never have an editor without a paragraph node, if you don't get them to work do a `test.skip(isPlainText || isCollab);` as a last resort. Nonetheless, great work here!

2024-03-29 21:09 UTC, ivailop7 commented
Also, don't forget to sort the imports for integrity to pass as well

2024-03-30 21:48 UTC, ivailop7 commented
@serey-roth I pushed a commit to your branch to help with the tests, let me know when you want to do more changes or you are done with this PR, so I can give this a proper read.

2024-03-30 22:08 UTC, serey-roth commented
> @serey-roth I pushed a commit to your branch to help with the tests, let me know when you want to do more changes or you are done with this PR, so I can give this a proper read.

@ivailop7 Thanks for taking care of the failing tests! I rewrote some of them last night, but it looks like I missed a few. I'm happy with the current changes. Please let me know if there's anything to adjust.

2024-03-30 22:44 UTC, ivailop7 commented
> > @serey-roth I pushed a commit to your branch to help with the tests, let me know when you want to do more changes or you are done with this PR, so I can give this a proper read.
> 
> @ivailop7 Thanks for taking care of the failing checks! I rewrote all my tests last night, but it looks like they weren't exactly correct. I'm happy with the current changes so please review them and let me know if there are anything I need to adjust.
> 
> Out of curiosity, how did you handle the missing paragraph in the collab editor?

Nothing really, removed all the extra code, I found it suspicious in a first place, since all other table tests should fail by the same logic and they didn't. I only added 'undefined' in the assertHTML methods, to not compare the left editor state with the right editor state, as it was done for the other table tests and things worked. I'll start reviewing now.

2024-03-30 22:53 UTC, ivailop7 commented on packages/lexical-table/src/LexicalTableSelectionHelpers.ts
> +        paragraphNode.selectEnd();
This chunk of code is the same as in the block under 'if (typeof payload === 'string')' above, worth exporting to a reusable method

2024-03-31 11:30 UTC, ivailop7 requested changes
Only the one method duplication comment, the rest is LGTM to me. @zurfyx can I get a second pair of eyes as well.

2024-03-31 20:54 UTC, serey-roth commented on packages/lexical-table/src/LexicalTableSelectionHelpers.ts
> +        paragraphNode.selectEnd();
All done!

2024-03-31 22:23 UTC, ivailop7 approved these changes
LGTM

2024-04-02 11:55 UTC, merged