add PR template
facebook/lexical pull request #5851
Opened 2024-04-09 02:54 UTC by potatowagon

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

2024-04-09 03:12 UTC, zurfyx reviewed
LGTM, but I'll let this PR sit for a bit to see if the rest have some opinions

2024-04-09 03:12 UTC, zurfyx commented on .github/pull_request_template.md
> +*Describe the changes in this diff*
[Opinionated] Let's use the closes tag, I also don't think we need an entire section to reference the issue, too much clutter.

```suggestion
## Description

*Describe the changes in this diff*

Closes #<issue>
```

2024-04-11 13:30 UTC, fantactuka commented on .github/pull_request_template.md
> +*Describe the changes in this diff*
nit: this pull request

2024-04-11 16:06 UTC, StyleT commented
Hi!

Let's add selection of the affected modules to the PR template, so we can sort them easier. Ex: [package name] (@lexical/core). This would allow people that recently worked on the respective packages to review PRs faster.

Also sorting by type would help: chore, docs, feat, bug...

2024-04-12 03:52 UTC, potatowagon commented
> Let's add selection of the affected modules to the PR template, so we can sort them easier. Ex: [package name] (@lexical/core). 
> Also sorting by type would help: chore, docs, feat, bug...

do u have an example of how this would fit into the PR template? youre welcomed to suggest a code change directly onto .github/pull_request_template.md

2024-04-15 18:31 UTC, StyleT requested changes

2024-04-15 18:31 UTC, StyleT commented on .github/pull_request_template.md
> +## Description
```suggestion
## What type of PR is this?

<!-- Please try to limit your pull request to one type (bugfix, feature, etc). Submit multiple pull requests if needed. -->
<!-- Leave 1 option from the list: -->
**Breaking change / Refactor / Feature / Bug Fix / Documentation Update / Chore**

## Description

<!-- Describe the changes in this pull request -->

**Current behavior:**
<!-- Please describe the current behavior that you are modifying. -->

**New behavior:**
<!-- Please describe the behavior or changes that are being added by this PR. -->

**Closes:** #<!-- issue number -->

**Affected packages:** <!-- List names of the affected packages within lexical monorepo. If none affected - put "infra" here.

## Test plan

### Before

*Insert relevant screenshots/recordings/automated-tests*

### After

*Insert relevant screenshots/recordings/automated-tests*

## Added/updated automated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests
```

2024-04-15 22:19 UTC, zurfyx commented on .github/pull_request_template.md
> +## Description
I wonder how much this will impact velocity. I like the detailed template as a means to write down as much information as possible but a too verbose summary will impact both the writers and the readers (I often find myself re-reading old PRs to understand the context).

IMO the package name should be part of the title, the close part can be part of the description and the automated tests don't need a checkbox list.

I'd advocate for a balance between @potatowagon 's initial PR and this.

2024-04-26 05:23 UTC, potatowagon commented on .github/pull_request_template.md
> +## Description
I added a title guidance, which prompts to list PR Type and lexical packages. reason: those info would be helpful when screening the list of pr titles of a sync diff.

For the description ive updated the guidance to include @StyleT suggestion. leaving that as guidance instead as the before/after behavior is covered in the test plan

2024-04-26 08:03 UTC, potatowagon commented on .github/workflows/test.yml
> +        # if: steps.cache.outputs.cache-hit != 'true'
not planning to commit this, temp fix to workflows error

>failed to load config from /Users/runner/work/lexical/lexical/packages/lexical-playground/vite.prod.config.ts
error during build:
Error: 
You installed esbuild on another platform than the one you're currently using.
This won't work because esbuild is written with native code and needs to
install a platform-specific binary executable.

Specifically the "esbuild-darwin-[64](https://github.com/facebook/lexical/actions/runs/8844961076/job/24287908130?pr=5851#step:8:65)" package is present but this platform
needs the "esbuild-darwin-arm64" package instead. People often get into this
situation by installing esbuild on Windows or macOS and copying "node_modules"
into a Docker image that runs Linux, or by copying "node_modules" between
Windows and WSL environments.

2024-04-29 04:08 UTC, StyleT approved these changes

2024-04-29 04:18 UTC, merged