Add h4 h5 h6 support to playground
facebook/lexical pull request #5881
Opened 2024-04-13 04:38 UTC by newproplus

Add h4 h5 h6 support to ToolbarPlugin and TableOfContentsPlugin

2024-04-15 02:15 UTC, potatowagon commented
hi! could u add screenshots of the before and after results? before could show what h1 to h3, and after could show h1 to h6

2024-04-15 02:21 UTC, potatowagon requested changes

2024-04-15 02:21 UTC, potatowagon commented on packages/lexical-playground/src/plugins/TableOfContentsPlugin/index.css
> -.table-of-contents .heading2 {
wont this break styling for heading 2?

style for heading2 deleted, but it is still used here: https://github.com/facebook/lexical/blob/616679a48175881c2a0f7970bbb438c59cbb8168/packages/lexical-playground/src/plugins/TableOfContentsPlugin/index.tsx#L24

2024-04-15 11:29 UTC, newproplus commented on packages/lexical-playground/src/plugins/TableOfContentsPlugin/index.css
> -.table-of-contents .heading2 {
The style of heading 2 here only has a 10px indentation. In order to shrink the indentation of all headings, especially for h6, I made heading 2 without any indentation.
I have standardized the styles of h1 to h6, making h1 have a larger font size. Additionally, the font sizes of h1 to h6 decrease gradually, ensuring that even h6 is still larger than regular text.


The previous image:
![1](https://github.com/facebook/lexical/assets/92970070/bc473e99-a4c9-4bb4-b861-321b8e20f8d1)


The image of my version:
![2](https://github.com/facebook/lexical/assets/92970070/23d3a59c-5592-4497-83d5-90c4515f4ee1)

2024-04-19 01:09 UTC, newproplus commented
I have standardized the styles of h1 to h6, making h1 have a larger font size. Additionally, the font sizes of h1 to h6 decrease gradually, ensuring that even h6 is still larger than regular text.

In order to shrink the indentation of all headings, especially for h6, I made heading 2 without any indentation.

The before image:
![1](https://github.com/facebook/lexical/assets/92970070/bc473e99-a4c9-4bb4-b861-321b8e20f8d1)


The after image:
![2](https://github.com/facebook/lexical/assets/92970070/23d3a59c-5592-4497-83d5-90c4515f4ee1)

2024-04-23 07:56 UTC, potatowagon commented on packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
> -  color: rgb(5, 5, 5);
this changes all the existing playground heading styles. the headings have been styled that way since https://github.com/facebook/lexical/commit/8b3945ef899b2dfe5abe849eca8e96ee3b9be30b

will defer to others who have more context if changing the current playground heading styles is ok. there could have been reasons why the current heading styles are as such

2024-04-23 13:12 UTC, newproplus commented on packages/lexical-playground/src/themes/PlaygroundEditorTheme.css
> -  color: rgb(5, 5, 5);
Due to uncertainty about whether the code here can be modified. I closed this PR.

2024-04-23 13:12 UTC, closed without merging