Fix selecting table selects an image after
facebook/lexical pull request #5917
Opened 2024-04-18 11:06 UTC by KatsiarynaDzibrova

Issue: selection of table by cursor dragging also selects the image after the table
Fix: resolve selection focus to the beginning of the paragraph with an image, not the root element with offset

Before:
![old-table-picture-select](https://github.com/facebook/lexical/assets/47710336/09ff93f0-f665-403f-922e-2a68f2d26990)

After:
![new-table-picture-select](https://github.com/facebook/lexical/assets/47710336/e04611bf-8e4b-4136-92a5-3170fef2b8c3)

2024-04-18 12:27 UTC, ivailop7 submitted a review, later dismissed

2024-04-18 21:36 UTC, zurfyx requested changes

2024-04-18 21:36 UTC, zurfyx commented on packages/lexical-table/src/LexicalTableSelectionHelpers.ts
> -                  : tableNode.getIndexWithinParent() + 1,
Let's check why this number is incorrect, that's the root cause of the issue. Notice that it will work if you remove the `+1`.

While the solution you have suggested is valid, it is equivalent of introducing a custom selection normalizer which I don't think that is what we want. In the hypothetical case we wanted this, we would probably prefer to improve `$normalizeSelection` (the common core module).

2024-04-19 21:29 UTC, ivailop7 approved these changes
LGTM

2024-04-21 21:14 UTC, ivailop7 commented
I'm happy here, any thoughts before I go for merge here, @zurfyx

2024-04-22 22:18 UTC, ivailop7 approved these changes

2024-04-22 22:29 UTC, merged