[lexical-devtools] Reflect picker state on inspector button ui
facebook/lexical pull request #6077
Opened 2024-05-10 09:39 UTC by 2wheeh

## Description

`EditorInspectorButton` reflects pickerActive state on UI.

**Closes:** #6068

## Test plan

### Before

https://github.com/facebook/lexical/assets/40269597/dec0b200-d955-4c04-8d3a-d04096f583bb

### After

https://github.com/facebook/lexical/assets/40269597/9ec3152e-75be-4722-9257-e6d5eee087f8

2024-05-13 16:14 UTC, StyleT requested changes
Hi! Thanks for this contribution!

Do you think it's possible to implements this via `ExtensionStore` instead of a bit quirky way when we try to keep sync via pending promise?

Also if done via store - we can sync that state to popup window as well easy peasy, while current approach makes it impossible

2024-05-14 02:15 UTC, 2wheeh commented
@StyleT Thanks ! I reverted and changed to utilize store. Please check the last commit

2024-05-14 02:43 UTC, StyleT reviewed
Looks much better now!

2024-05-14 02:43 UTC, StyleT commented on packages/lexical-devtools/src/store.ts
> +  isSelecting: boolean;
It should be per tab, as other values. As you may have 2 windows/tabs where you do selection "in parallel".

I have it in plans to make store work "per tab/window" by default, but I'm not there yet :P

2024-05-14 16:08 UTC, 2wheeh commented on packages/lexical-devtools/src/store.ts
> +  isSelecting: boolean;
reverted the last commit because manipulating externalStore before reactDOM createRoot makes page restricted somehow and was also over the scope of this PR.

2024-05-14 22:53 UTC, StyleT approved these changes
Awesome work!

2024-05-15 17:33 UTC, merged