Fix: Bug - 6000: Changing the font size when inputting does not take …
facebook/lexical pull request #6102
Opened 2024-05-14 16:00 UTC by pixelbyaj

…effect

## Description

*Describe the changes in this pull request*

**Closes:** #

## Test plan

### Before

*Insert relevant screenshots/recordings/automated-tests*

### After

*Insert relevant screenshots/recordings/automated-tests*

2024-05-14 16:34 UTC, StyleT requested changes
Awesome work! Can you pls add screen recordings before/after + add (if possible) some automated tests.

Let me know if you need any help with tests.

2024-05-14 17:42 UTC, pixelbyaj commented
### Before:

https://github.com/facebook/lexical/assets/740916/8ad37d7a-974b-456c-9d44-0fc3219950e8

### After:

https://github.com/facebook/lexical/assets/740916/a053411e-3834-4bc7-ad6d-746d5b49027e

2024-05-14 19:42 UTC, ivailop7 submitted a review, later dismissed

2024-05-14 20:27 UTC, StyleT approved these changes

2024-05-16 17:08 UTC, ivailop7 approved these changes

2024-05-16 17:09 UTC, merged