Refactor import paths in LexicalEditorState
facebook/lexical pull request #6178
Opened 2024-05-27 17:33 UTC by vuki365

[lexical] Refactor: Change import paths syntax in LexicalEditorState

Description

The current behavior implements not consistent import approaches which can lead to confusion.

This pull request addresses the issue by using consistent import syntax to make it easier to understand
which module is from where imported.

2024-05-28 09:36 UTC, potatowagon requested changes

2024-05-28 09:36 UTC, potatowagon commented on packages/lexical/src/LexicalEditorState.ts
> +import {$isElementNode} from './nodes/LexicalElementNode';
these should auto sort upon saving if not try

```
./node_modules/.bin/eslint ./ --fix
```

2024-05-28 09:36 UTC, potatowagon commented on packages/lexical/src/LexicalEditorState.ts
> +
nit: pls remove the extra line (tho auto fix should solve that)

2024-05-30 09:09 UTC, potatowagon approved these changes
lgtm

2024-05-30 09:41 UTC, vuki365 commented
Thanks :)

2024-05-31 05:09 UTC, merged