[lexical][lexical-overflow] Refactor: simplified removeText and insertText rewrite (part 1)
facebook/lexical pull request #6456
Opened 2024-07-24 21:48 UTC by GermanJablo

This is something I've been wanting to do since I did the insertNodes rewrite. These are also methods with long and very complex implementations.

Currently, removeText depends on insertText, since removeText is defined as inserting an empty string (`insertText("")`). This PR seeks to reverse the dependency of these methods, making insertText dependent on removeText.

This can be achieved in 2 steps:
1. Rewrite `removeText` without making it dependent on insertText.
2. Rewrite `insertText` with the new removeText.

So far in this PR, I have managed to complete step 1 and 95% of step 2. I decided to leave step 2 for a later PR because there are about 4 tests that fail and, after having dedicated so much time to it, I want to do a pause on this.

2024-07-24 21:51 UTC, GermanJablo commented on packages/lexical-overflow/src/index.ts
> +  }
It's likely that `insert/removeText` currently has some logic that prevents this. If it works in all cases, I don't know.

Ensuring that an overFlowNode cannot be empty in lexical-overflow is a more robust and less error-prone solution, and it frees up the load on other packages.

2024-07-24 21:55 UTC, GermanJablo commented on packages/lexical/src/LexicalSelection.ts
> +
Once the failing tests are fixed and this implementation is activated, 364 lines of code can be removed (`$transferStartingElementPointToTextPoint` is only used in the current implementation of `insertText`).

2024-07-25 02:45 UTC, GermanJablo commented on packages/lexical-playground/__tests__/e2e/Mentions.spec.mjs
>      await assertSelection(page, {
I coincidentally noticed that the `if` and `else` blocks are the same here

2024-07-25 20:34 UTC, etrepum commented on packages/lexical/src/LexicalSelection.ts
> +    }
I think this fixes the bugs in here related to fixing up the selection

```suggestion
    const fixText = (
      node: TextNode,
      point: PointType,
      delCount: number,
    ): TextNode | null => {
      if (node.getTextContent() === '') {
        node.remove();
        return null;
      } else if (delCount !== 0 && $isTokenOrSegmented(node)) {
        const textNode = $createTextNode(node.getTextContent());
        textNode.setFormat(node.getFormat());
        textNode.setStyle(node.getStyle());
        point.set(textNode.getKey(), point.offset, 'text');
        return node.replace(textNode);
      } else {
        return node;
      }
    };
    if (firstNode === lastNode && $isTextNode(firstNode)) {
      const delCount = Math.abs(focus.offset - anchor.offset);
      firstNode.spliceText(firstPoint.offset, delCount, '');
      const attachedNode = fixText(firstNode, firstPoint, delCount);
      if (attachedNode) {
        attachedNode.select(firstPoint.offset, firstPoint.offset);
      }
      return;
    }
    if ($isTextNode(lastNode)) {
      lastNode.spliceText(0, lastPoint.offset, '');
      const attachedNode = fixText(lastNode, lastPoint, lastPoint.offset);
      if (attachedNode) {
        attachedNode.selectStart();
      }
    }
    if ($isTextNode(firstNode)) {
      const delCount = firstNode.getTextContentSize() - firstPoint.offset;
      firstNode.spliceText(firstPoint.offset, delCount, '');
      const attachedNode = fixText(firstNode, firstPoint, delCount);
      if (attachedNode) {
        attachedNode.selectEnd();
      }
    }
```

2024-07-25 20:35 UTC, etrepum commented on packages/lexical/src/LexicalSelection.ts
> +    }
Although there's probably another case to handle when both nodes are removed and you need to select the parent

2024-07-25 21:12 UTC, etrepum commented on packages/lexical/src/LexicalSelection.ts
> +      lastNode = fixText(firstNode, del) || lastNode;
An explicit selection here might make sense, since right now this depends on node.replace doing the right thing with the selection under certain circumstances

2024-07-25 21:15 UTC, GermanJablo commented on packages/lexical/src/LexicalSelection.ts
> +      lastNode = fixText(firstNode, del) || lastNode;
Look at lines 1156-9 :)

2024-07-25 21:17 UTC, etrepum commented on packages/lexical/src/LexicalSelection.ts
> +      lastNode = fixText(firstNode, del) || lastNode;
Look at line 1145 😉

2024-07-25 22:01 UTC, GermanJablo commented on packages/lexical/src/LexicalSelection.ts
> +    }
I saw your suggestion after I submitted my last fix. I haven't tested that snippet but the current version works. Thanks a lot!

2024-07-25 22:05 UTC, GermanJablo commented on packages/lexical/src/LexicalSelection.ts
> +      lastNode = fixText(firstNode, del) || lastNode;
Ah yes, I see what you mean. The variable reassignment here is unnecessary, I've removed it.

Nothing needs to be done with the selection here as replace handles selection correction just fine (I wrote that code).

As a side note, I think fixText should actually be part of spliceText, just like how replace handles selection normalization. Maybe I should do that in another PR.

2024-07-25 23:45 UTC, etrepum commented on packages/lexical/src/LexicalSelection.ts
> +      lastNode = fixText(firstNode, del) || lastNode;
I wrote some unit tests to verify that it does seem to be doing what I expected and they all passed

```diff
diff --git a/packages/lexical/src/__tests__/unit/LexicalSelection.test.ts b/packages/lexical/src/__tests__/unit/LexicalSelection.test.ts
index 7055f361a..de1e6cd8e 100644
--- a/packages/lexical/src/__tests__/unit/LexicalSelection.test.ts
+++ b/packages/lexical/src/__tests__/unit/LexicalSelection.test.ts
@@ -9,15 +9,20 @@
 import {$createLinkNode, $isLinkNode} from '@lexical/link';
 import {
   $createParagraphNode,
+  $createRangeSelection,
   $createTextNode,
   $getRoot,
+  $getSelection,
   $isParagraphNode,
   $isTextNode,
+  $setSelection,
   LexicalEditor,
+  ParagraphNode,
   RangeSelection,
+  TextNode,
 } from 'lexical';
 
-import {initializeUnitTest, invariant} from '../utils';
+import {$assertRangeSelection, initializeUnitTest, invariant} from '../utils';
 
 describe('LexicalSelection tests', () => {
   initializeUnitTest((testEnv) => {
@@ -338,5 +343,156 @@ describe('LexicalSelection tests', () => {
         });
       });
     });
+    describe('removeText', () => {
+      describe('with a leading TextNode and a trailing segmented TextNode', () => {
+        let leadingText: TextNode;
+        let trailingSegmentedText: TextNode;
+        let paragraph: ParagraphNode;
+        beforeEach(() => {
+          testEnv.editor.update(
+            () => {
+              leadingText = $createTextNode('leading text');
+              trailingSegmentedText =
+                $createTextNode('segmented text').setMode('segmented');
+              paragraph = $createParagraphNode().append(
+                leadingText,
+                trailingSegmentedText,
+              );
+              $getRoot().clear().append(paragraph);
+            },
+            {discrete: true},
+          );
+        });
+        test('remove all text', () => {
+          testEnv.editor.update(
+            () => {
+              const sel = $createRangeSelection();
+              sel.anchor.set(leadingText.getKey(), 0, 'text');
+              sel.focus.set(
+                trailingSegmentedText.getKey(),
+                trailingSegmentedText.getTextContentSize(),
+                'text',
+              );
+              $setSelection(sel);
+              sel.removeText();
+              expect(leadingText.isAttached()).toBe(false);
+              expect(trailingSegmentedText.isAttached()).toBe(false);
+              expect($getRoot().getAllTextNodes()).toHaveLength(0);
+              const selection = $assertRangeSelection($getSelection());
+              expect(selection.isCollapsed()).toBe(true);
+              expect(selection.anchor.key).toBe(paragraph.getKey());
+              expect(selection.anchor.offset).toBe(0);
+            },
+            {discrete: true},
+          );
+        });
+        test('remove initial TextNode', () => {
+          testEnv.editor.update(
+            () => {
+              const sel = $createRangeSelection();
+              sel.anchor.set(leadingText.getKey(), 0, 'text');
+              sel.focus.set(
+                leadingText.getKey(),
+                leadingText.getTextContentSize(),
+                'text',
+              );
+              $setSelection(sel);
+              sel.removeText();
+              expect(leadingText.isAttached()).toBe(false);
+              expect(trailingSegmentedText.isAttached()).toBe(true);
+              expect($getRoot().getAllTextNodes()).toHaveLength(1);
+              const selection = $assertRangeSelection($getSelection());
+              expect(selection.isCollapsed()).toBe(true);
+              expect(selection.anchor.key).toBe(trailingSegmentedText.getKey());
+              expect(selection.anchor.offset).toBe(0);
+            },
+            {discrete: true},
+          );
+        });
+        test('remove trailing segmented TextNode', () => {
+          testEnv.editor.update(
+            () => {
+              const sel = $createRangeSelection();
+              sel.anchor.set(trailingSegmentedText.getKey(), 0, 'text');
+              sel.focus.set(
+                trailingSegmentedText.getKey(),
+                trailingSegmentedText.getTextContentSize(),
+                'text',
+              );
+              $setSelection(sel);
+              sel.removeText();
+              expect(leadingText.isAttached()).toBe(true);
+              expect(trailingSegmentedText.isAttached()).toBe(false);
+              expect($getRoot().getAllTextNodes()).toHaveLength(1);
+              const selection = $assertRangeSelection($getSelection());
+              expect(selection.isCollapsed()).toBe(true);
+              expect(selection.anchor.key).toBe(leadingText.getKey());
+              expect(selection.anchor.offset).toBe(
+                leadingText.getTextContentSize(),
+              );
+            },
+            {discrete: true},
+          );
+        });
+        test('remove initial TextNode and partial segmented TextNode', () => {
+          testEnv.editor.update(
+            () => {
+              const sel = $createRangeSelection();
+              sel.anchor.set(leadingText.getKey(), 0, 'text');
+              sel.focus.set(
+                trailingSegmentedText.getKey(),
+                'segmented '.length,
+                'text',
+              );
+              $setSelection(sel);
+              sel.removeText();
+              expect(leadingText.isAttached()).toBe(false);
+              // expecting a new node since it was segmented
+              expect(trailingSegmentedText.isAttached()).toBe(false);
+              const allTextNodes = $getRoot().getAllTextNodes();
+              expect(allTextNodes.map((node) => node.getTextContent())).toEqual(
+                ['text'],
+              );
+              const selection = $assertRangeSelection($getSelection());
+              expect(selection.isCollapsed()).toBe(true);
+              expect(selection.anchor.key).toBe(allTextNodes[0].getKey());
+              expect(selection.anchor.offset).toBe(0);
+            },
+            {discrete: true},
+          );
+        });
+        test('remove partial initial TextNode and partial segmented TextNode', () => {
+          testEnv.editor.update(
+            () => {
+              const sel = $createRangeSelection();
+              sel.anchor.set(leadingText.getKey(), 'lead'.length, 'text');
+              sel.focus.set(
+                trailingSegmentedText.getKey(),
+                'segmented '.length,
+                'text',
+              );
+              $setSelection(sel);
+              sel.removeText();
+              expect(leadingText.isAttached()).toBe(true);
+              expect(trailingSegmentedText.isAttached()).toBe(false);
+              const allTextNodes = $getRoot().getAllTextNodes();
+              // These should get merged in reconciliation
+              expect(allTextNodes.map((node) => node.getTextContent())).toEqual(['lead', 'text']);
+              const selection = $assertRangeSelection($getSelection());
+              expect(selection.isCollapsed()).toBe(true);
+              expect(selection.anchor.key).toBe(leadingText.getKey());
+              expect(selection.anchor.offset).toBe('lead'.length);
+            },
+            {discrete: true},
+          );
+          testEnv.editor.getEditorState().read(() => {
+            const allTextNodes = $getRoot().getAllTextNodes();
+            // These should get merged in reconciliation
+            expect(allTextNodes.map((node) => node.getTextContent())).toEqual(['leadtext']);
+            expect(leadingText.isAttached()).toBe(true);
+          })
+        });
+      });
+    });
   });
 });
```

2024-07-26 11:17 UTC, GermanJablo commented on packages/lexical/src/LexicalSelection.ts
> +      lastNode = fixText(firstNode, del) || lastNode;
Thanks @etrepum. I've already added it. Adding you as a PR contributor is something only maintainers can do, right? If so, please "CC @mantainers"

2024-08-04 04:01 UTC, etrepum approved these changes
LGTM - not sure if you were planning to extend this PR or follow-up afterwards

2024-08-04 04:01 UTC, etrepum commented on packages/lexical/src/LexicalSelection.ts
> +
Do you expect to add that to this PR, or after this one lands?

2024-08-04 15:20 UTC, GermanJablo commented
Yes, to be continued in another PR

2024-08-05 16:41 UTC, etrepum commented
I think some of the E2E tests are failing, I was hoping that it was just flakiness but it has consistently failed since I turned on extended tests. #6488 is passing (after a flaky test failure) which is based on the same main commit.

2024-08-06 08:18 UTC, potatowagon commented
> I think some of the E2E tests are failing, I was hoping that it was just flakiness but it has consistently failed since I turned on extended tests. #6488 is passing (after a flaky test failure) which is based on the same main commit.

yea quite abit of e2e plaintext tests failures that are not known to be flaky: https://github.com/facebook/lexical/actions/runs/10251936357/job/28361149775?pr=6456

2024-08-06 16:07 UTC, etrepum requested changes
Waiting for e2e test fixes before merge

2024-08-25 21:53 UTC, GermanJablo commented
done @etrepum

2024-08-26 05:55 UTC, etrepum approved these changes
Could use another set of eyes on this one since it's such a fundamental change to removeText

2024-08-26 07:20 UTC, ivailop7 commented
Let's do 0.17.1 first and then do this one as a 0.18 with the defaults change.

2024-08-26 16:35 UTC, GermanJablo commented on packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleTitleNode.ts
> +  static transform(): (node: LexicalNode) => void {
Not always. If you remove this you will see that some tests fail because there may be empty CollapsibleTitleNodes.
Apparently, it wasn't necessary because it was one of the many things that `insertText` did.

2024-08-26 17:21 UTC, ivailop7 commented on packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleTitleNode.ts
> +  static transform(): (node: LexicalNode) => void {
OK, let's update those tests and remove the transform part from the node, since when people copy-paste the Playground it would create more confusion, if it's purely there for tests to pass.

2024-08-26 18:05 UTC, etrepum commented on packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleTitleNode.ts
> +  static transform(): (node: LexicalNode) => void {
I think both may be necessary for correct behavior, not just tests. The container won't be empty if it has an empty title since it's measured by children and not text, so the empty title is removed first and then the next pass removes the container

2024-08-26 19:11 UTC, GermanJablo commented on packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleTitleNode.ts
> +  static transform(): (node: LexicalNode) => void {
Yes, it's not just about the tests. I don't see anything wrong or confusing here. It's a pattern that other nodes use.

2024-08-26 19:14 UTC, ivailop7 commented on packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleTitleNode.ts
> +  static transform(): (node: LexicalNode) => void {
That's the part that confuses me, the Layout plugin should be in the same boat by that rule, since it's near identical implementation to the Collapsible Plugin, unless it's purely because we are missing tests for it and the transform method should be added to the Layout plugin as well?

2024-08-26 19:27 UTC, GermanJablo commented on packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleTitleNode.ts
> +  static transform(): (node: LexicalNode) => void {
As a general rule I think it's a good idea to use transforms to make sure that nodes that should be used together can't be orphaned.
I don't know what the layout plugin is but I think improving that would be out of scope of this PR.

PS: I updated the branch and there is a flaky test that failed. Can you please restart it?

2024-08-26 19:46 UTC, etrepum commented on packages/lexical-playground/src/plugins/CollapsiblePlugin/CollapsibleTitleNode.ts
> +  static transform(): (node: LexicalNode) => void {
I think in general we are missing transforms for a handful of nodes to guarantee correct behavior, e.g. the merge-unmerge issue with TableCellNode not having paragraph children. The static transform method is experimental and new-ish, previously you had to have the correct editor and/or plugin configuration to have all of the required transforms. I would agree that adding other transforms is out of scope for this PR, unless the previous removeText implementation also handled them.

2024-08-27 08:56 UTC, ivailop7 approved these changes
Approving, trusting you both you have this planned out. Haven't spent much time getting the whole context here.

2024-09-04 23:37 UTC, merged

2024-10-01 14:58 UTC, adrianmxb commented
I am a bit late to the party but the changes here break removal of TextNodes in `token` and `segmented` mode.

![CleanShot 2024-10-01 at 15 58 03](https://github.com/user-attachments/assets/abf6778d-05b1-4672-9ae7-6b84baee7641)

2024-10-01 15:24 UTC, GermanJablo commented
Isn't that supposedly the correct behavior, or am I missing something? Are you sure it worked differently before? There were a lot of those tests I had to pass.